### ISSUE TITLE
Hmm...

### ISSUE THREAD

**Issue by Pub4Game** [luca28pet/AdvancedKits#10]
I don't know, maybe I'm wrong....

I go to the server and enter the command /kit basicpvp. Everything is fine! Then I wrote /kit basicbuilder and he writes to me that I've already got it, although it is not so!

**Comment by luca28pet** [comment]
To have more than 1 kit per life you have to edit one-kit-per-life to false in config.yml

**Comment by Pub4Game** [comment]
Then make a message That "you can't get more than 1 kit per life" Thanks for the reply
