### ISSUE TITLE
Players Not Being able to use kits

### ISSUE THREAD

**Issue by totaljerkface216** [luca28pet/AdvancedKits#100]
Ive tried a lot of things and ive ran out of ideas. i cant set permissions for pureperm groups. i dont know if im doing something wrong. 
![screenshot_10](https://cloud.githubusercontent.com/assets/16735444/24933504/8b48651c-1ecb-11e7-9824-2467c1aaeb36.png)
ive tried the following

**Comment by totaljerkface216** [comment]
nvm im stupid i looked at other problems like this and found out that there is no caps

**Comment by AffanStarPure** [comment]
U should put advancedkits.(name)  on name u kit u add then put same name on kit permission advancedkits.starter

**Comment by totaljerkface216** [comment]
I put caps before when i was not suppose d to sorry everything good now
