### ISSUE TITLE
I cant use it in pmmp

### ISSUE THREAD

**Issue by XDqrkneZ** [luca28pet/AdvancedKits#105]
Unhandled exception executing command 'kit pickaxe' in kit: Call to undefined method pocketmine\item\enchantment\Enchantment::getEnchantmentByName()
[14:04:35] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\item\enchantment\Enchantment::getEnchantmentByName()" (EXCEPTION) in "/AdvancedKits_v5.1/src/AdvancedKits/Kit" at line 105

**Comment by SourSmirnoff** [comment]
same problem here, have you found a resolution?

**Comment by XDqrkneZ** [comment]
@soursmirnoff no :( it’s most like because PMMP doesn’t use getEnchantByName

**Comment by SourSmirnoff** [comment]
have you found a working kit plugin?

**Comment by luca28pet** [comment]
I have changed the method name, you can use it in PMMP
