### ISSUE TITLE
No permission

### ISSUE THREAD

**Issue by BudderSticks** [luca28pet/AdvancedKits#107]
So i loce ths plugin but whenever a non op player tries to get a kit they dont have permission. They are trying ti get the kit in the world i specified and i added them to the list. But no change

I am using pureperms

**Comment by luca28pet** [comment]
If you are using PurePerms you have to give them this permission:
advancedkits.kitname
Whereas kitname is the name of the kit that you want them to get, in lowercase

**Comment by DarknessGaming** [comment]
Is not working
