### ISSUE TITLE
Error:-

### ISSUE THREAD

**Issue by optimusprime338** [luca28pet/AdvancedKits#108]
using latest comming,
console error:-
29.06 12:54:08 [Server] Server thread/CRITICAL Error: "Call to undefined method pocketmine\item\enchantment\Enchantment::getEffectByName()" (EXCEPTION) in "AdvancedKits_v5.1.phar/src/AdvancedKits/Kit" at line 105
29.06 12:54:08 [Server] Server thread/CRITICAL Unhandled exception executing command 'kit Visitor' in kit: Call to undefined method pocketmine\item\enchantment\Enchantment::getEffectByName()

**Comment by luca28pet** [comment]
Use pmmp

**Comment by optimusprime338** [comment]
I am using pmmp latest

**Comment by luca28pet** [comment]
Are you using master branch?

**Comment by optimusprime338** [comment]
I am using a version from poggit CI

**Comment by luca28pet** [comment]
You have to use the master branch
