### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by LolNova** [luca28pet/AdvancedKits#109]
[TSP] [00:44:19] [CRITICAL]: Unhandled exception executing command 'kit testkit' in kit: Call to undefined method pocketmine\item\enchantment\Enchantment::getEffectByName()
30.06 02:44:19 [Server] INFO [TSP] [00:44:19] [CRITICAL]: Error: "Call to undefined method pocketmine\item\enchantment\Enchantment::getEffectByName()" (EXCEPTION) in "/AdvancedKits_v5.1.phar/src/AdvancedKits/Kit" at line 105

**Comment by XFizzer** [comment]
Use pmmp

**Comment by LolNova** [comment]
pmmp is bad. Why can't the owner of advance kits just make it for all systems

**Comment by MasterOfTheRealm** [comment]
@LolNova Check out my fork of AdvancedKits if you want it working forks
