### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by xXCyrerXx** [luca28pet/AdvancedKits#11]
PocketMine-MP Crash Dump Sun Aug 9 11:30:09 UTC 2015

Error: Call to a member function reduceMoney() on boolean
File: /AdvancedKits_v3.phar/src/AdvancedKits/EconomyManager
Line: 30
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: AdvancedKits v3

Code:
[21]         }
[22]     }
[23] 
[24]     public function grantKit(Player $player, $money){
[25]         if(is_null($this->economy)){
[26]             return false;
[27]         }
[28]         switch($this->economy){
[29]             case "EconomyAPI":
[30]                 if($this->api->reduceMoney($player, $money) === 1){
[31]                     return true;
[32]                 }
[33]             break;
[34]             case "PocketMoney":
[35]                 if($this->api->getMoney($player->getName()) < $money){
[36]                     return false;
[37]                 }
[38]                 if($this->api->setMoney($player->getName(), $this->api->getMoney($player->getName()) - $money)){
[39]                     return true;
[40]                 }

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #0 [Protocol 33; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.4.5-4439001 #1 SMP PREEMPT Fri Mar 20 20:34:59 KST 2015 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
ZipPluginLoader 1.1.2 by aliuly for API(s) 1.10.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
EasyMOTD 1.0a by LDX for API(s) 1.12.0
AdvancedKits 3 by luca28pet for API(s) 1.12.0
PurePerms 1.1.7 by 64FF00 for API(s) 1.12.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
ManyWorlds 2.0.1 by aliuly for API(s) 1.10.0
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
GrabBag 2.2.7 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0
CommandTracker 1.0.1 by Scott Handley for API(s) 1.10.0
KillHeart 1.0.0 by BukkitPlaysMC for API(s) 1.0.0
EconomyAPI 2.0.7 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
CustomAreas 1 by luca28pet for API(s) 1.12.0
SignStatus 2 by xpyctum for API(s) 1.0.0
VoteBan 1.0.2 by GmWM for API(s) 1.12.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
CombatLogger 1.2.0 by Lambo for API(s) 1.12.0
PocketDockConsole 0.0.14 by humerusj for API(s) 1.0.0
SimpleAuthHelper 1.3.0dev2 by aliuly for API(s) 1.10.0
FactionsPro 1.4.1 by Tethered_, HostingItAll.com for API(s) 1.12.0
KillRate 1.2.3 by aliuly for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNW4lvGze6/1f4lAJrLzS6fanrAq7jHKid6MVO87DVwqBmKGnquTrk2FaL/O/v933kXLKzOdYt
1kjrmY/kd18kx390TBirznQ4GR8Nh0eHg6NuR+V5mnemf3TMJsNQ5+z67N27t+863U6stJYrgp3K
KBImFVLEKl6oXCyLxDdhmohcBYWvLtJEbXZ2BQCLNI2UTLB8GUa0tn8S3MrEV8FPodHXt+NetpZ5
X+d+a6B/5qdJGm8uZAKSOZZHYYLl48HHbieLilWYAFdzBab4aaCI89EQY8L9fMTAaOQA/DLGC/2e
OGBWLKLQr2VY5TIxQLkzi+QGwn2X8e+u+C4muXb/oMV7DRLhcifU10kRRTvfmXWovR+U5X7Xzt1v
zKWfXJkiT8RSRlp9TxMOtvk9bAD0XWj89TZmRny0hdiXWol5x+nuZPZ6jgndzniwNc8x7VDKLPR+
aBpuW2BxfHwshkxyPHwEVUMmkxcs0nj0yDwSbTzeGljkSt7wksnj0sxS/0YZ5syJs/d5cVZuRSkL
Q97IWO3s7op/NC053v/3ElVWGh98SqTDz/OjP80P1PyljHsl45bzoy+zxWTwKOMIJJNLHxHzS+fZ
QOzsTkXGqo4RafP5pcpvibyfS71+XsTZjgvl3c6/up2VSlQuI4o2zNIIG9AY9vYDdQuKiyKMgs50
gFDNU5P6KSaOx90OJORpw3FvgGmr0OB18IU/WJDLmyhc0JreAWMoEkn5q3MeJsW9iFJfRutUGzHu
TXp73gRpbTAYimdDcXkxE7N3Z2cXsyvxIg/FhczFaIB/0/Fkunckfrq8wstwT8g8vj2IgDpbZ0C8
19vvjfD2u0ogUGeE14EdvE51SRgAfpFJkKdh0KlSlCb9/DPMZvx2nspAcWp1XG+PdFu6HDJhWZh1
mmsykozCItqQ9lmPv9CcAdgBQCVyESlwSDbvdgKVgV9ahDGdLs3zJiCWnDy3qM/nFwRHosUrhi+v
Tt5dvZ8BcKcWOjTE8NqYTE/7fRhuXSx6fhr3ZaR+ZbnBXL/2H88poG9ypfqx1Ebl/W15oafLcJXM
0txYV3J6aQA/o5Kjo0ilib+Wyaqll3Fv+K1qqRAeHSEIKk621TN7e3n14e278+efU1CDxX5DMMh+
JvXm4u3V84bkFagt90C2xT5//n9tNxh9uxsA13xe0v1mKYHFuzidnfUrCSBgqzzXQm5V7UrQcUvG
qPDl6DBT5skkbdL9ZkErtlrtCkk7K3I1U3ncFLWGbTvyQdui+5MXLwaDJxP12uKbzysGGo9fHeO8
0sVzjQUif0jzKDgLQnOSm4bULfCWJ/cG1wtl5DUKxfWzweSwrYbZ2YXMLtKAskNTF/9BmstULLOY
Uc7nd8SZAmcyN/P5Fp9f6woNZvuXMVpi75+n3uyRvNeiA7Whqd0wrOkqDWBTZXAC5LI/sw5YdPN5
DAZYP18WHNTuUhKLM2P5bqaxGvjA/J+XZfSfy6KIARbmLyhrr988P/u535CZ61qcReoEgrbqWgVs
q+Vg28Su5wVFcaVkjEG9Tlfr0M+eTFU1M1TmGox9ZW6oOO03sEADL3O5+FGuGuKXkLZ7j7ZT4afc
u0sPw/LhCZwE+7zFQq6+uRR8jY+UskMxp2mMUAuu0HvftNrBrYHtyNlykUs/NUa8woJIPV0yaPMw
nz/g6dPe4RLCT2EUvVKyVRBq2GfSwY/FzU1oaN+tL06fqgK0kM7nFTNfleaqLXUzzdXA7ZS95dPY
tC3w3wOJ2JXd71H1e8i/x+597N4n7n3y7b2tYwP50XIOXtD7NaX4AlWcFtqk8Qm27c3y1YQ2lDH8
k3u6BtknaOmaQrjNyaWRptBbmxMHbMg5asl5n218U8RP5cA1Sbsjqch/gbV+To36USYNAUrIdihu
ba1exh8unsxMhGw+d5Srhy+T4I0ya5WfrpVu7SJa4O3ueviXdBmJ8on8X1JAWuLaKrKQ5jxdrbZr
SA1ua2W0nWzPZbxIn24fSdi4YFQMfE2CtX3Ec/z/NE10GqnmLurBWFOyAdXGSVu0dRGrvNC/PlUE
PuDgm23+ANNDSLt/fKWirGXiB0NtM6NsYG/1BEdHzXb1C4Jhzcx8jclfSD5v17M8bYjXhLYlm2yH
9RXHhAquu+JVqk2YrF6bkygiPT+ZWzfYmc/dy5eLSL3GO2nUVi/EoO3oHP8Ju7zm4XmHNp5ah7fK
VfxOt93BvEyj4NIEnYe2vQHPOXj+SzJdpaCPdI4qc6gN4FI8PpXuZXkKZzOhomPXZ7PqTSCEluFK
0F3TPJ8nzy6LRJwUK3EkhsPpaDQdD8X7q1M+6qVxi84j0xyfwriFFq8TvzGSpbk5Hh4NxyMCrjAv
TgN1PKC3WN579pBeHw8HDNKZvEs8OvRW7CnHIwbfraGZKNTmOF0uCWAt6P1WqHxznCYNUA6LlLMC
pf08zBjRqyJBRhUvwYH+H6aemuAh1LFNd3fHSZrHMuK54DrfeFEYh5BmdHhBwAjq9oosgKpLgjJJ
0iLxlRPLk/46VLcqVonRjs3bUN15AUShsy+IzcuiKL3zllG4WlcSWk3IJAQL5VoLi9NFCVjLPPDT
vKKf3WZuJAiXy9AvIrM5HrLm+b7BpLmnlaFI18csA7iLrPl4tz+qgVqpoDGHNfL87MXJ+/MrgpKe
exniAeuC47/zDyQpTOppeascG2w4r2m5ZZpDP5UjOChdCVRe3dvEEbmloGARPntkAebpbpEcUwCH
qPfN3iVCFq4qrlDclSjlEzJXAvlNIHY1HqQRPtnHiIUSYeJHRaACPIgHIUG4LtMYK5eEYBunlkvV
FSmlTk0o7Q2c2KRF7nCJcCkgXbgMmQIslMOdkQiA+I26q9D1A7WUsJEWd2nyNyNklmFfJUiJMcT1
4RcbugOm6y0r+d1aJaLIsPMOgKA3T8hjLbLpPBHPrtZIBF4EELiIZLIq5EoJutdlpTnv1iHe+bIn
/J3VSkvRGvlOivZCMFBmJJX07sKbMFNBKHtpvurTW/8c5r1Ol9evL99e74+PvNE1rYMaK0RTMUfS
Xc07ROjDmssO3X9rpFlBd+Ha5Kxfk8tER4iowA6zNplT8IEnZdikKNChr8SaN+8EiYHYelZNki8e
AdfrwgQpBY69fydm7OWc8KNUq8CydUJBKMhVwYlwiVXchlL8L2UZTOFsU6bcKV8P0sLLNdZJ8lNq
PoSjYk0lHSJRaDghCg0cgaVDxcBMFKuA9FQPeGBrAaZq9Gec10o8kFhQxAu4KzyCWF1shPMjTHdZ
sBqt8XxAWYAt4VEyCESutHU84hKudgNupC5yzlUC7rZQpA7oXP1WSP5YYYXKl4hbGRVK7DiKKAS7
QG7JIfkqyvcejEnt61SgSIDym4K/cUA0nehN4l9JfQOHz28QPz0afw8bsHuWMtKsdY7KinJiMFt3
BWcn4bIYPLYLLcRQmqYGgLWC+kmwuEgQODSFcV+yx0AexFae3iObopBsSBz29KRijZRq2Xm9pADl
zzMQiF0Rmr/R1xo5rwoUVSZ2wq21YgcSwMxiRBphGTwn5ZQxUbDaQsKh+jJKF1As9RvCggXXF0pJ
sVrJxcaAIXFpWRkw8VCTdW2gQ6a7kBljZQsqIa5OOZBmvSxDeAuyFLJ4wqiWSBElRWt+CFOwz65S
yJFSZJDOQGfFTNrCN4WxJ4dzThacmQ2SjQz+yyWgTqzkfzgYTSz/M5WHKWd/8n1NSH3Ofw5r5d9D
+AIiOyCb8gyP+jhShUWEfgn5AhEBJikYPyWD5R3lMOKESrFlp825whEOeHsdOTZqicJbClkqKDy9
93AyRavraKHsTPlUdzTrhHi11rBrKwGQcFWmazHHAyen3n2UISf12Eq9kvkCyvb8NIpsn0Ye/ahW
2XbEilsj3BrESiyTgitckwvU/wJes9stY3DLbZzf2Dy2XJaxGNf+2BNvbXnhN430nxZRUDESImLv
ElGzTk4iMuYcAu4PBlZG8ewFu92DXMS+YldXQi3zNC5TGq11414zCzRsCiGc6bZd4RH/aayjhtlf
F8mNtvo+52ijBMRA4ow2FiSNKD9BoljIUe+1neRRyaXWocZFqEozu0A52nd8Pk/tsm3zUdKlxsQu
a2KwVNy0J5CZE7/nSzopYqmdL5SEaKAqcv8W1TxJlCFbVJ0SXCOylWchDVp1qvt0Tm9QcOBPLn9x
ANo+0I3atLVQVQ1CD1HWGuex5QgFfr4xhLsrvGHDmanWMFnPlKwgrezt26xS1zZuv6mwBDbXOQPa
tQA6nnriFbYPUO8xWk847unsfRdrwcEC+ecuDMzapkiO7wq9x+in4sAV4rpEa1ZMY2pPnASIp7WM
ln301LZrCBT8zBECSet/adIMyKoaNnDV3dmzs3sKPmo7ZNS1gU2EP4QJmjaIBbdR7NpUW9/PkllZ
mesWmZoOWnSH7dCc+uMk89wrt0COFm0IF8Vq6or8D2JIxd0aU1MTx8NlA6c5j61V2djNnSlQRuq2
TIu+5sPkruivfKtauu/RtduVu6lWl67Klo3YhiB2f8JTnXeRtGxvHzo07GBuiWeXTEWMoZXr3iEP
H2YQt/A4+CjnJNnCj8RJ+x/TIA9dmofccIiy5Z69eXt1NhWcdPHPL7CVSbCVYUR8vkWWY/Yc5Yq9
ysInLWPxlzyqlJWdiCsSOCGnMeQ4o4GrIJTJbGEiL6LNJcFdNXJB3waXKWzPRaQthAv6FLKmtTNE
mDxCpCtGGBg+NqCM39vlkNWqyQQ7wxVhpn2MO84QCmnJ0qPCbw3JO8Z6K0lpgLcc1KhQMpDRndxo
i9vhqb2olbzZiU7itEia2V+77qjkgbgnZNSf05EGHpFgPr1U5oAGlnWLo11yxPDo8dXsW4mye7aF
stgWaklpiI8sKF2RFSqs9iCjkfds2ruUt6i4tO0LaWuqaKuTbdw23BWiqpvhLLHkI68yJ7octiwi
npZqOKpH8Rn6to7wfienvS/8AmhLVf2a0rbDRoaWMblKzImSqkslf5VGrDFIoaUxLuS9kNt6wYbD
5+JQu0PLFgNa+Q47+UI3VjkzSMccR6hd6byO5qNToXxEB0buCKrmD7taJS0NPnl5wHi9iyp57z1k
3iW/Oxnyfhh730I5+7r1HPQM9zSMNRWH34QtS7MictjcM9WlLcTzhEPSg/aIaXsu5rEfQfIJNW0w
eELeUEGHLjnQedRU2M6uNCl9iFtk6HRsu2cdklOH7TIcLmA5oFWOoHZbWghChCogw2S8COH5doo7
CrMb4qnNRbR1p4+BhYXaAuucxHqva+Or1EZ+7dFhShtSFZMWNFtnYbJMaz+gL3mnlmSvcbqGLoj5
S9JkE1OPzxGioV9dMUqbFjcs6mFmGM4mhVytUHvcTrw64qAGkT6JvnlcGssPodOP8UP6sr7MJt5e
DZ+wo1NrgDzxXGWu2z+GppneInl3d/cYwShELrcyn91LqmX2hXoBeKu7XZgK98BDcCVtUjjOL/To
IYNjpwLAvwijzTFliW+eG3JJL1txux8qD2R5o/PYMSTvG7lEaK7GFDgxinQIRl35bLDOVJkBfhJ0
fEuBMeG3itpUvDg/uZqOvj/o7h3dD7vj+3F39P3w+wBlzuaEHbpL8Cl+jw8H9LccWtu3yd4uH9Sq
e6MSUgjfJp8iyze+8w74sqZ6RbJddabskN1O5tNU96J/i0KjxvZbdM9+9v67/TjdXrQufPQM62o+
HQEmgcxrgP37mvKtyKPqZRlGhq78gNp98LQ0WTW6iuvnNWLDXt9j0q+6ukuii7J4YU8lq8notzaZ
qSUwkhgKGuJezs6ZKj1nPvqkeu0GAvMn8O5J7NG165AkFx7dp4wGe4Mx/YXCa9htOT4YK7kXBHt7
48OD/eFksC8PB6ORnCwO5fhgMhkeLkaTgRLfgdJsTWrhz2aYcKrD+1rpbh9cfgpJgr5TS7eJA5Tp
Haq9pS/RBU5AdrA8OPAPDg/39/ZAenw0GqvxYHF0cBQETE+v47RWoebA0m1JQ6t8TDbpjUqQxfMK
8kHJm1wtraJ6e4BsJB/4lx8e/B5m9m3Um3Q+fvx/qbjxBA==
===END CRASH DUMP===PocketMine-MP Crash Dump Sun Aug 9 11:30:09 UTC 2015

Error: Call to a member function reduceMoney() on boolean
File: /AdvancedKits_v3.phar/src/AdvancedKits/EconomyManager
Line: 30
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: AdvancedKits v3

Code:
[21]         }
[22]     }
[23] 
[24]     public function grantKit(Player $player, $money){
[25]         if(is_null($this->economy)){
[26]             return false;
[27]         }
[28]         switch($this->economy){
[29]             case "EconomyAPI":
[30]                 if($this->api->reduceMoney($player, $money) === 1){
[31]                     return true;
[32]                 }
[33]             break;
[34]             case "PocketMoney":
[35]                 if($this->api->getMoney($player->getName()) < $money){
[36]                     return false;
[37]                 }
[38]                 if($this->api->setMoney($player->getName(), $this->api->getMoney($player->getName()) - $money)){
[39]                     return true;
[40]                 }

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #0 [Protocol 33; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.4.5-4439001 #1 SMP PREEMPT Fri Mar 20 20:34:59 KST 2015 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
ZipPluginLoader 1.1.2 by aliuly for API(s) 1.10.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
EasyMOTD 1.0a by LDX for API(s) 1.12.0
AdvancedKits 3 by luca28pet for API(s) 1.12.0
PurePerms 1.1.7 by 64FF00 for API(s) 1.12.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
ManyWorlds 2.0.1 by aliuly for API(s) 1.10.0
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
GrabBag 2.2.7 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0
CommandTracker 1.0.1 by Scott Handley for API(s) 1.10.0
KillHeart 1.0.0 by BukkitPlaysMC for API(s) 1.0.0
EconomyAPI 2.0.7 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
CustomAreas 1 by luca28pet for API(s) 1.12.0
SignStatus 2 by xpyctum for API(s) 1.0.0
VoteBan 1.0.2 by GmWM for API(s) 1.12.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
CombatLogger 1.2.0 by Lambo for API(s) 1.12.0
PocketDockConsole 0.0.14 by humerusj for API(s) 1.0.0
SimpleAuthHelper 1.3.0dev2 by aliuly for API(s) 1.10.0
FactionsPro 1.4.1 by Tethered_, HostingItAll.com for API(s) 1.12.0
KillRate 1.2.3 by aliuly for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNW4lvGze6/1f4lAJrLzS6fanrAq7jHKid6MVO87DVwqBmKGnquTrk2FaL/O/v933kXLKzOdYt
1kjrmY/kd18kx390TBirznQ4GR8Nh0eHg6NuR+V5mnemf3TMJsNQ5+z67N27t+863U6stJYrgp3K
KBImFVLEKl6oXCyLxDdhmohcBYWvLtJEbXZ2BQCLNI2UTLB8GUa0tn8S3MrEV8FPodHXt+NetpZ5
X+d+a6B/5qdJGm8uZAKSOZZHYYLl48HHbieLilWYAFdzBab4aaCI89EQY8L9fMTAaOQA/DLGC/2e
OGBWLKLQr2VY5TIxQLkzi+QGwn2X8e+u+C4muXb/oMV7DRLhcifU10kRRTvfmXWovR+U5X7Xzt1v
zKWfXJkiT8RSRlp9TxMOtvk9bAD0XWj89TZmRny0hdiXWol5x+nuZPZ6jgndzniwNc8x7VDKLPR+
aBpuW2BxfHwshkxyPHwEVUMmkxcs0nj0yDwSbTzeGljkSt7wksnj0sxS/0YZ5syJs/d5cVZuRSkL
Q97IWO3s7op/NC053v/3ElVWGh98SqTDz/OjP80P1PyljHsl45bzoy+zxWTwKOMIJJNLHxHzS+fZ
QOzsTkXGqo4RafP5pcpvibyfS71+XsTZjgvl3c6/up2VSlQuI4o2zNIIG9AY9vYDdQuKiyKMgs50
gFDNU5P6KSaOx90OJORpw3FvgGmr0OB18IU/WJDLmyhc0JreAWMoEkn5q3MeJsW9iFJfRutUGzHu
TXp73gRpbTAYimdDcXkxE7N3Z2cXsyvxIg/FhczFaIB/0/Fkunckfrq8wstwT8g8vj2IgDpbZ0C8
19vvjfD2u0ogUGeE14EdvE51SRgAfpFJkKdh0KlSlCb9/DPMZvx2nspAcWp1XG+PdFu6HDJhWZh1
mmsykozCItqQ9lmPv9CcAdgBQCVyESlwSDbvdgKVgV9ahDGdLs3zJiCWnDy3qM/nFwRHosUrhi+v
Tt5dvZ8BcKcWOjTE8NqYTE/7fRhuXSx6fhr3ZaR+ZbnBXL/2H88poG9ypfqx1Ebl/W15oafLcJXM
0txYV3J6aQA/o5Kjo0ilib+Wyaqll3Fv+K1qqRAeHSEIKk621TN7e3n14e278+efU1CDxX5DMMh+
JvXm4u3V84bkFagt90C2xT5//n9tNxh9uxsA13xe0v1mKYHFuzidnfUrCSBgqzzXQm5V7UrQcUvG
qPDl6DBT5skkbdL9ZkErtlrtCkk7K3I1U3ncFLWGbTvyQdui+5MXLwaDJxP12uKbzysGGo9fHeO8
0sVzjQUif0jzKDgLQnOSm4bULfCWJ/cG1wtl5DUKxfWzweSwrYbZ2YXMLtKAskNTF/9BmstULLOY
Uc7nd8SZAmcyN/P5Fp9f6woNZvuXMVpi75+n3uyRvNeiA7Whqd0wrOkqDWBTZXAC5LI/sw5YdPN5
DAZYP18WHNTuUhKLM2P5bqaxGvjA/J+XZfSfy6KIARbmLyhrr988P/u535CZ61qcReoEgrbqWgVs
q+Vg28Su5wVFcaVkjEG9Tlfr0M+eTFU1M1TmGox9ZW6oOO03sEADL3O5+FGuGuKXkLZ7j7ZT4afc
u0sPw/LhCZwE+7zFQq6+uRR8jY+UskMxp2mMUAuu0HvftNrBrYHtyNlykUs/NUa8woJIPV0yaPMw
nz/g6dPe4RLCT2EUvVKyVRBq2GfSwY/FzU1oaN+tL06fqgK0kM7nFTNfleaqLXUzzdXA7ZS95dPY
tC3w3wOJ2JXd71H1e8i/x+597N4n7n3y7b2tYwP50XIOXtD7NaX4AlWcFtqk8Qm27c3y1YQ2lDH8
k3u6BtknaOmaQrjNyaWRptBbmxMHbMg5asl5n218U8RP5cA1Sbsjqch/gbV+To36USYNAUrIdihu
ba1exh8unsxMhGw+d5Srhy+T4I0ya5WfrpVu7SJa4O3ueviXdBmJ8on8X1JAWuLaKrKQ5jxdrbZr
SA1ua2W0nWzPZbxIn24fSdi4YFQMfE2CtX3Ec/z/NE10GqnmLurBWFOyAdXGSVu0dRGrvNC/PlUE
PuDgm23+ANNDSLt/fKWirGXiB0NtM6NsYG/1BEdHzXb1C4Jhzcx8jclfSD5v17M8bYjXhLYlm2yH
9RXHhAquu+JVqk2YrF6bkygiPT+ZWzfYmc/dy5eLSL3GO2nUVi/EoO3oHP8Ju7zm4XmHNp5ah7fK
VfxOt93BvEyj4NIEnYe2vQHPOXj+SzJdpaCPdI4qc6gN4FI8PpXuZXkKZzOhomPXZ7PqTSCEluFK
0F3TPJ8nzy6LRJwUK3EkhsPpaDQdD8X7q1M+6qVxi84j0xyfwriFFq8TvzGSpbk5Hh4NxyMCrjAv
TgN1PKC3WN579pBeHw8HDNKZvEs8OvRW7CnHIwbfraGZKNTmOF0uCWAt6P1WqHxznCYNUA6LlLMC
pf08zBjRqyJBRhUvwYH+H6aemuAh1LFNd3fHSZrHMuK54DrfeFEYh5BmdHhBwAjq9oosgKpLgjJJ
0iLxlRPLk/46VLcqVonRjs3bUN15AUShsy+IzcuiKL3zllG4WlcSWk3IJAQL5VoLi9NFCVjLPPDT
vKKf3WZuJAiXy9AvIrM5HrLm+b7BpLmnlaFI18csA7iLrPl4tz+qgVqpoDGHNfL87MXJ+/MrgpKe
exniAeuC47/zDyQpTOppeascG2w4r2m5ZZpDP5UjOChdCVRe3dvEEbmloGARPntkAebpbpEcUwCH
qPfN3iVCFq4qrlDclSjlEzJXAvlNIHY1HqQRPtnHiIUSYeJHRaACPIgHIUG4LtMYK5eEYBunlkvV
FSmlTk0o7Q2c2KRF7nCJcCkgXbgMmQIslMOdkQiA+I26q9D1A7WUsJEWd2nyNyNklmFfJUiJMcT1
4RcbugOm6y0r+d1aJaLIsPMOgKA3T8hjLbLpPBHPrtZIBF4EELiIZLIq5EoJutdlpTnv1iHe+bIn
/J3VSkvRGvlOivZCMFBmJJX07sKbMFNBKHtpvurTW/8c5r1Ol9evL99e74+PvNE1rYMaK0RTMUfS
Xc07ROjDmssO3X9rpFlBd+Ha5Kxfk8tER4iowA6zNplT8IEnZdikKNChr8SaN+8EiYHYelZNki8e
AdfrwgQpBY69fydm7OWc8KNUq8CydUJBKMhVwYlwiVXchlL8L2UZTOFsU6bcKV8P0sLLNdZJ8lNq
PoSjYk0lHSJRaDghCg0cgaVDxcBMFKuA9FQPeGBrAaZq9Gec10o8kFhQxAu4KzyCWF1shPMjTHdZ
sBqt8XxAWYAt4VEyCESutHU84hKudgNupC5yzlUC7rZQpA7oXP1WSP5YYYXKl4hbGRVK7DiKKAS7
QG7JIfkqyvcejEnt61SgSIDym4K/cUA0nehN4l9JfQOHz28QPz0afw8bsHuWMtKsdY7KinJiMFt3
BWcn4bIYPLYLLcRQmqYGgLWC+kmwuEgQODSFcV+yx0AexFae3iObopBsSBz29KRijZRq2Xm9pADl
zzMQiF0Rmr/R1xo5rwoUVSZ2wq21YgcSwMxiRBphGTwn5ZQxUbDaQsKh+jJKF1As9RvCggXXF0pJ
sVrJxcaAIXFpWRkw8VCTdW2gQ6a7kBljZQsqIa5OOZBmvSxDeAuyFLJ4wqiWSBElRWt+CFOwz65S
yJFSZJDOQGfFTNrCN4WxJ4dzThacmQ2SjQz+yyWgTqzkfzgYTSz/M5WHKWd/8n1NSH3Ofw5r5d9D
+AIiOyCb8gyP+jhShUWEfgn5AhEBJikYPyWD5R3lMOKESrFlp825whEOeHsdOTZqicJbClkqKDy9
93AyRavraKHsTPlUdzTrhHi11rBrKwGQcFWmazHHAyen3n2UISf12Eq9kvkCyvb8NIpsn0Ye/ahW
2XbEilsj3BrESiyTgitckwvU/wJes9stY3DLbZzf2Dy2XJaxGNf+2BNvbXnhN430nxZRUDESImLv
ElGzTk4iMuYcAu4PBlZG8ewFu92DXMS+YldXQi3zNC5TGq11414zCzRsCiGc6bZd4RH/aayjhtlf
F8mNtvo+52ijBMRA4ow2FiSNKD9BoljIUe+1neRRyaXWocZFqEozu0A52nd8Pk/tsm3zUdKlxsQu
a2KwVNy0J5CZE7/nSzopYqmdL5SEaKAqcv8W1TxJlCFbVJ0SXCOylWchDVp1qvt0Tm9QcOBPLn9x
ANo+0I3atLVQVQ1CD1HWGuex5QgFfr4xhLsrvGHDmanWMFnPlKwgrezt26xS1zZuv6mwBDbXOQPa
tQA6nnriFbYPUO8xWk847unsfRdrwcEC+ecuDMzapkiO7wq9x+in4sAV4rpEa1ZMY2pPnASIp7WM
ln301LZrCBT8zBECSet/adIMyKoaNnDV3dmzs3sKPmo7ZNS1gU2EP4QJmjaIBbdR7NpUW9/PkllZ
mesWmZoOWnSH7dCc+uMk89wrt0COFm0IF8Vq6or8D2JIxd0aU1MTx8NlA6c5j61V2djNnSlQRuq2
TIu+5sPkruivfKtauu/RtduVu6lWl67Klo3YhiB2f8JTnXeRtGxvHzo07GBuiWeXTEWMoZXr3iEP
H2YQt/A4+CjnJNnCj8RJ+x/TIA9dmofccIiy5Z69eXt1NhWcdPHPL7CVSbCVYUR8vkWWY/Yc5Yq9
ysInLWPxlzyqlJWdiCsSOCGnMeQ4o4GrIJTJbGEiL6LNJcFdNXJB3waXKWzPRaQthAv6FLKmtTNE
mDxCpCtGGBg+NqCM39vlkNWqyQQ7wxVhpn2MO84QCmnJ0qPCbw3JO8Z6K0lpgLcc1KhQMpDRndxo
i9vhqb2olbzZiU7itEia2V+77qjkgbgnZNSf05EGHpFgPr1U5oAGlnWLo11yxPDo8dXsW4mye7aF
stgWaklpiI8sKF2RFSqs9iCjkfds2ruUt6i4tO0LaWuqaKuTbdw23BWiqpvhLLHkI68yJ7octiwi
npZqOKpH8Rn6to7wfienvS/8AmhLVf2a0rbDRoaWMblKzImSqkslf5VGrDFIoaUxLuS9kNt6wYbD
5+JQu0PLFgNa+Q47+UI3VjkzSMccR6hd6byO5qNToXxEB0buCKrmD7taJS0NPnl5wHi9iyp57z1k
3iW/Oxnyfhh730I5+7r1HPQM9zSMNRWH34QtS7MictjcM9WlLcTzhEPSg/aIaXsu5rEfQfIJNW0w
eELeUEGHLjnQedRU2M6uNCl9iFtk6HRsu2cdklOH7TIcLmA5oFWOoHZbWghChCogw2S8COH5doo7
CrMb4qnNRbR1p4+BhYXaAuucxHqva+Or1EZ+7dFhShtSFZMWNFtnYbJMaz+gL3mnlmSvcbqGLoj5
S9JkE1OPzxGioV9dMUqbFjcs6mFmGM4mhVytUHvcTrw64qAGkT6JvnlcGssPodOP8UP6sr7MJt5e
DZ+wo1NrgDzxXGWu2z+GppneInl3d/cYwShELrcyn91LqmX2hXoBeKu7XZgK98BDcCVtUjjOL/To
IYNjpwLAvwijzTFliW+eG3JJL1txux8qD2R5o/PYMSTvG7lEaK7GFDgxinQIRl35bLDOVJkBfhJ0
fEuBMeG3itpUvDg/uZqOvj/o7h3dD7vj+3F39P3w+wBlzuaEHbpL8Cl+jw8H9LccWtu3yd4uH9Sq
e6MSUgjfJp8iyze+8w74sqZ6RbJddabskN1O5tNU96J/i0KjxvZbdM9+9v67/TjdXrQufPQM62o+
HQEmgcxrgP37mvKtyKPqZRlGhq78gNp98LQ0WTW6iuvnNWLDXt9j0q+6ukuii7J4YU8lq8notzaZ
qSUwkhgKGuJezs6ZKj1nPvqkeu0GAvMn8O5J7NG165AkFx7dp4wGe4Mx/YXCa9htOT4YK7kXBHt7
48OD/eFksC8PB6ORnCwO5fhgMhkeLkaTgRLfgdJsTWrhz2aYcKrD+1rpbh9cfgpJgr5TS7eJA5Tp
Haq9pS/RBU5AdrA8OPAPDg/39/ZAenw0GqvxYHF0cBQETE+v47RWoebA0m1JQ6t8TDbpjUqQxfMK
8kHJm1wtraJ6e4BsJB/4lx8e/B5m9m3Um3Q+fvx/qbjxBA==
===END CRASH DUMP===

**Comment by xXCyrerXx** [comment]
Sry i clicked paste 2 timesa

**Comment by luca28pet** [comment]
Please use the latest version
