### ISSUE TITLE
SIGN_POST errors

### ISSUE THREAD

**Issue by XElectricX** [luca28pet/AdvancedKits#110]
Amazing plugin that I have been using for months, but these errors have been showing up and spamming my console to the point of making it unreadable. Seems to only happen when players are online. Using Tesseract 1.3.0-Dev.

`[CRITICAL] Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'AdvancedKits v5.1': Undefined class constant 'SIGN_POST' on AdvancedKits\EventListener`
`[CRITICAL] Error: "Undefined class constant 'SIGN_POST'" (EXCEPTION) in "/AdvancedKits_v5.1[Tesseract].phar/src/AdvancedKits/EventListener" at line 25`

**Comment by MasterOfTheRealm** [comment]
They provide no support for software other than pmmp

**Comment by MSG100TC** [comment]
I had that error too. But I just can't find a working pmmp phar.

**Comment by XElectricX** [comment]
I would use PMMP if enchants actually worked... at least on Tesseract, all the enchants are there.
