### ISSUE TITLE
Enchants? Help!

### ISSUE THREAD

**Issue by MSG100TC** [luca28pet/AdvancedKits#113]
[08:05:46] [Server thread/CRITICAL]: Unhandled exception executing command 'kit archer' in kit: Call to undefined method pocketmine\item\enchantment\Enchantment::getEnchantmentByName()
[08:05:46] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\item\enchantment\Enchantment::getEnchantmentByName()" (EXCEPTION) in "/phar_AdvancedKits-master_8j0l4kRAYNOVR2H.phar/src/AdvancedKits/Kit" at line 105

**Comment by XElectricX** [comment]
Are you using a server software other than PMMP?

**Comment by MSG100TC** [comment]
tesseract 1.3.0

I don't know how to use pmmp.

**Comment by MSG100TC** [comment]
PMMP can't get enchant too somehow.

**Comment by XElectricX** [comment]
Just use the Tesseract version.

**Comment by MSG100TC** [comment]
No, there are even more errors with tesseract while using AdvancedKits. If using tesseract, AdvancedKits causes the Slapper plugin loads of errors. And The "sign post" comes up and blocks player's "hits". And the "[Warning] Blocked ip Adress (ip) for 5 seconds" error comes up too when player keep hitting.

**Comment by XElectricX** [comment]
I only got the sign post errors. Not sure about those other ones.

**Comment by MSG100TC** [comment]
Can you send me the server phar kind you used? Mine just don't want me to make a server XD

**Comment by XElectricX** [comment]
This dude has a link for it: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=0ahUKEwiT8eG31ajVAhXKrFQKHfyKCsMQtwIIODAD&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DFuFfj7X3zpY&usg=AFQjCNGuLygfZPLL22kp_ZnnGz7RxqO8pg

**Comment by luca28pet** [comment]
This should be fixed in the latest commit

**Comment by MSG100TC** [comment]
Latest commit?
