### ISSUE TITLE
Enchants not working with PMMP api3/blocks branch

### ISSUE THREAD

**Issue by optimusprime338** [luca28pet/AdvancedKits#115]
Can you please have a look why enchant is not working with latest PMMP api3/blocks branch?? Although other functions are working fine.

**Comment by MSG100TC** [comment]
Yup, it doesn't work with PMMP.

**Comment by optimusprime338** [comment]
it work with master branch . do cheack it!

**Comment by MSG100TC** [comment]
Can you give me a link to that? I can't find it for an hour.

**Comment by optimusprime338** [comment]
https://github.com/pmmp/PocketMine-MP/tree/api3/blocks
