### ISSUE TITLE
Enchants Not Working...

### ISSUE THREAD

**Issue by MSG100TC** [luca28pet/AdvancedKits#117]
I'm using  PocketMine-MP 1.6.2dev-188 「Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)

error: [11:11:47] [Server thread/CRITICAL]: Unhandled exception executing command 'kit god' in kit: Call to undefined method pocketmine\item\enchantment\Enchantment::getEnchantmentByName()
[11:11:47] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\item\enchantment\Enchantment::getEnchantmentByName()" (EXCEPTION) in "/AdvancedKits_v5.1/src/AdvancedKits/Kit" at line 105

Enchants don't work with pmmp master branch?

**Comment by MSG100TC** [comment]
Heeeeeeeeeeeeelp!!!

Please why doesn't it work on PMMP master?

**Comment by luca28pet** [comment]
This should be fixed with the latest commit
