### ISSUE TITLE
Exception:- getEffectByName

### ISSUE THREAD

**Issue by optimusprime338** [luca28pet/AdvancedKits#119]
Console error:-
```
 [Server thread/CRITICAL]: Unhandled exception executing command 'kit Voter' in kit: Call to undefined method pocketmine\item\enchantment\Enchantment::getEffectByName()
[13:29:22] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\item\enchantment\Enchantment::getEffectByName()" (EXCEPTION) in "AdvancedKits.phar/src/AdvancedKits/Kit" at line 105
```
 
latest plugin
pmmp latest:- https://poggit.pmmp.io/ci/pmmp/PocketMine-MP/~/dev:1366

**Comment by MSG100TC** [comment]
Enchants never work. Sadly, on pmmp.

**Comment by optimusprime338** [comment]
It does ..!!

**Comment by MSG100TC** [comment]
No it doesn't. I've used the pmmp 1.6.2 dev alpha 6 on jenkins and the enchantments still didn't work.

**Comment by optimusprime338** [comment]
I am using API3-ALPHA7 ..Enchats works awesome. Make sure u are using pmmp master branch!!!

**Comment by optimusprime338** [comment]
It might also be that u are not able to do correct configurations.

**Comment by luca28pet** [comment]
This should be fixed with the latest commit
