### ISSUE TITLE
Enchants

### ISSUE THREAD

**Issue by optimusprime338** [luca28pet/AdvancedKits#120]
Enchants stopped working on latest commit :- 06ac3c4
pmmp version :- 1.6.2dev+poggit.1398

**Comment by luca28pet** [comment]
Please provide error message and kits.yml and how to reproduce this

**Comment by optimusprime338** [comment]
there are actully no errors it just not enchanting .. I am using default kit testkit ..

**Comment by optimusprime338** [comment]
working all fine! closing this issue . thanks for support.
