### ISSUE TITLE
Enchants Not Working on weapons

### ISSUE THREAD

**Issue by MSG100TC** [luca28pet/AdvancedKits#121]
Armor enchants work fine. But it isn't working on weapons.
Heres the line of the sword enchant:

`- "276:0:1:OP Sword:sharpness:3"`

**Comment by luca28pet** [comment]
do they get added to the sword?

**Comment by MSG100TC** [comment]
I don't get what you mean by that...

Enchant are not added to the sword. It only gave me a normal one.

**Comment by optimusprime338** [comment]
@MSG100TC  ur config is wrong
it should be ``` - "276:0:1:OP:Sword:sharpness:3" ``` not ``` - "276:0:1:OP Sword:sharpness:3" ```
kindly close this issue

**Comment by MSG100TC** [comment]
Oops, I'm very for the confusion... I typed it wrong here...But correct in config. My bad

**Comment by optimusprime338** [comment]
why did you reopened it??

**Comment by MSG100TC** [comment]
It's correct 
"276:0:1:OP:Sword:sharpness:3"
In config.

I made a typo "here"

**Comment by optimusprime338** [comment]
-.- just copy my config below:-
"276:0:1:OPSWord:sharpness:3"

**Comment by NycuRO** [comment]
Same.

**Comment by NycuRO** [comment]
- "276:0:1:Diamond Sword:sword_sharpness:1"

**Comment by optimusprime338** [comment]
coz of latest API changes enchants >3 don't work  and its only "sharpness" now instead of "sword_sharpness"
