### ISSUE TITLE
Kits not working with any software

### ISSUE THREAD

**Issue by AyanKR** [luca28pet/AdvancedKits#122]
The plugin isnt working with any software
it shows this Fatal error: Declaration of AdvancedKits\Main::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool must be compatible with pocketmine\command\CommandExecutor::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, $label, array $args) in phar:///plugins/AdvancedKits_v5.2.phar/src/AdvancedKits/Main.php on line 119
it crashes the server and in genisys when i do /kit starter it doesnt give me anything but does show you have recieved the kit

**Comment by luca28pet** [comment]
You are using an outdated version of PocketMine-MP
