### ISSUE TITLE
Undefined index: lang_version

### ISSUE THREAD

**Issue by Pub4Game** [luca28pet/AdvancedKits#13]
ArrayOutOfBoundsException: "Undefined index: lang_version" (E_NOTICE) in "/AdvancedKits-master/src/AdvancedKits/lang/LangManager" at line 37

Error starting plugin

**Comment by luca28pet** [comment]
The version you downloaded is still in early development, for production servers it's better to use the latest stable release.
However thanks for submitting, I will fix ASAP

**Comment by Pub4Game** [comment]
Make support for multiple languages) I will help you with the translation plugin on Russian language

**Comment by Pub4Game** [comment]
@luca28pet Fatal error: Cannot use object of type pocketmine\utils\Config as array in C:\PocketMine-MP\plugins\AdvancedKits-master\src\AdvancedKits\lang\LangManager.php on line 37
