### ISSUE TITLE
Enchants not implemented

### ISSUE THREAD

**Issue by timbersquirrel** [luca28pet/AdvancedKits#132]
Please try to fix this, you can’t /enchant and item with a ench id over 2 so they only have implemented 3 enchants and I can’t create kits with other enchants

**Comment by Awzaw** [comment]
Until luca28pet decides to update his plugins, or asks us to remove them from Poggit, you can get an updated version here:
https://poggit.pmmp.io/p/AdvancedKits

**Comment by timbersquirrel** [comment]
Please try to implement all of the enchants @Awzaw
