### ISSUE TITLE
combined commands

### ISSUE THREAD

**Issue by K1llerJ0hnny** [luca28pet/AdvancedKits#14]
Ok, so what im trying to do is that when i get a kit  and i do  /clearinv  it wont let me get another kit it will tell me that you already have a kit. Then i changed the config file and it still doesn't work at all. Anyway of helping me?

**Comment by luca28pet** [comment]
Try setting one-kit-per-life: false in the config.yml and restart the server

**Comment by K1llerJ0hnny** [comment]
ok that worked, but like is there anyway they cant get the kit multiple times XD, because i making a kitpvp server and i want them to be allowed to switch kits, and not got get the kit more than once. You know what i mean?
