### ISSUE TITLE
Pureperms

### ISSUE THREAD

**Issue by servantthought** [luca28pet/AdvancedKits#142]
In the group chat permissions on pureperms I added this permission line"Custom permission support: give a player permission advancedkits.kitname to let him use the kit named "kitname""

I haven't been able to get it to work it keeps saying I dont have permission for the kit assigned to my group or any other kit

**Comment by artulloss** [comment]
use poggit orphanage fork

**Comment by servantthought** [comment]
What is that?

**Comment by artulloss** [comment]
Poggit-orphanage revives dead plugins.
https://github.com/poggit-orphanage/AdvancedKits
