### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by servantthought** [luca28pet/AdvancedKits#145]
11.05 16:02:32 [Server] Server thread/CRITICAL Unhandled exception executing command 'kit starter' in kit: Call to undefined method pocketmine\entity\Effect::setDuration() 11.05 16:02:32 [Server] Server thread/CRITICAL Error: "Call to undefined method pocketmine\entity\Effect::setDuration()" (EXCEPTION) in "AdvancedKits/src/AdvancedKits/Kit" at line 130 11.05 16:02:32 [Server] Server thread/DEBUG #0 AdvancedKits/src/AdvancedKits/Kit(86): AdvancedKits\Kit->loadEffect(string speed, integer 1000, integer 1) 11.05 16:02:32 [Server] Server thread/DEBUG #1 AdvancedKits/src/AdvancedKits/Kit(52): AdvancedKits\Kit->addTo(pocketmine\Player object) 11.05 16:02:32 [Server] Server thread/DEBUG #2 AdvancedKits/src/AdvancedKits/Main(70): AdvancedKits\Kit->handleRequest(pocketmine\Player object) 11.05 16:02:32 [Server] Server thread/DEBUG #3 src/pocketmine/command/PluginCommand(58): AdvancedKits\Main->onCommand(pocketmine\Player object, pocketmine\command\PluginCommand object, string kit, array Array()) 11.05 16:02:32 [Server] Server thread/DEBUG #4 src/pocketmine/command/SimpleCommandMap(258): pocketmine\command\PluginCommand->execute(pocketmine\Player object, string kit, array Array()) 11.05 16:02:32 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1946): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string kit starter) 11.05 16:02:32 [Server] Server thread/DEBUG #6 src/pocketmine/Player(2188): pocketmine\Server->dispatchCommand(pocketmine\Player object, string kit starter) 11.05 16:02:32 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(222): pocketmine\Player->chat(string /kit starter

**Comment by luca28pet** [comment]
Please download the latest release from https://poggit.pmmp.io/p/AdvancedKits/5.2.1
