### ISSUE TITLE
You haven't permission to use kit starter?

### ISSUE THREAD

**Issue by djcjf** [luca28pet/AdvancedKits#147]
Hi there I am new to Advanced Kit and want to use the default starter kit on my PvP survival server but is gives me the error In the title. I want all players to be able to get the kit for free when needed. Any Help Is Greatly Appreciated Thanks! :D

**Comment by fycarman** [comment]
You can give them the permission "advancedkits.kitname" through your permission manager plugin (pureperms, if you use it).
remember that the permission should be in lowercase, so if the kit is named "Starter", the permission would be "advancedkits.starter".
