### ISSUE TITLE
AdvancedKits doesn't load because of error

### ISSUE THREAD

**Issue by AndreasHGK** [luca28pet/AdvancedKits#156]
The plugin has an error when i start the server. I used the latest dev-26 build. I also get an error with dev-24. There's not much else to say. To recreate it you just start the server. Note that i did use customenchants. This might be because i used CE

CONSOLE:
19.06 10:39:16 [Server] Server thread/INFO Enabling AdvancedKits v5.2.3 19.06 10:39:16 [Server] Server thread/NOTICE PiggyCustomEnchants detected. Activated custom enchants support 19.06 10:39:16 [Server] Server thread/NOTICE FormAPI detected. Activated kit selection UI support 19.06 10:39:16 [Server] Server thread/CRITICAL RuntimeException: "Dynamic field access on pocketmine\nbt\tag\CompoundTag is no longer supported" (EXCEPTION) in "vendor/pocketmine/nbt/src/tag/NoDynamicFieldsTrait" at line 29 19.06 10:39:16 [Server] Server thread/DEBUG #0 vendor/pocketmine/nbt/src/tag/NoDynamicFieldsTrait(41): pocketmine\nbt\tag\CompoundTag->throw() 19.06 10:39:16 [Server] Server thread/DEBUG #1 PiggyCustomEnchants.phar/src/PiggyCustomEnchants/Main(489): pocketmine\nbt\tag\CompoundTag->__isset(string ench) 19.06 10:39:16 [Server] Server thread/DEBUG #2 AdvancedKits_dev-26.phar/src/AdvancedKits/Kit(238): PiggyCustomEnchants\Main->addEnchantment(pocketmine\item\Axe object, array Array(), array Array()) 19.06 10:39:16 [Server] Server thread/DEBUG #3 AdvancedKits_dev-26.phar/src/AdvancedKits/Kit(52): AdvancedKits\Kit->loadItem(string 279:0:1:..r..6..lThor's hammer..r:sharpness:1:lightning:3:unbreaking:10) 19.06 10:39:16 [Server] Server thread/DEBUG #4 AdvancedKits_dev-26.phar/src/AdvancedKits/Main(129): AdvancedKits\Kit->__construct(AdvancedKits\Main object, array Array(), string thor) 19.06 10:39:16 [Server] Server thread/DEBUG #5 AdvancedKits_dev-26.phar/src/AdvancedKits/Main(45): AdvancedKits\Main->loadKits() 19.06 10:39:16 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/PluginBase(90): AdvancedKits\Main->onEnable() 19.06 10:39:16 [Server] Server thread/DEBUG #7 src/pocketmine/plugin/PharPluginLoader(127): pocketmine\plugin\PluginBase->setEnabled(boolean 1) 19.06 10:39:16 [Server] Server thread/DEBUG #8 src/pocketmine/plugin/PluginManager(576): pocketmine\plugin\PharPluginLoader->enablePlugin(AdvancedKits\Main object) 19.06 10:39:16 [Server] Server thread/DEBUG #9 src/pocketmine/Server(1919): pocketmine\plugin\PluginManager->enablePlugin(AdvancedKits\Main object) 19.06 10:39:16 [Server] Server thread/DEBUG #10 src/pocketmine/Server(1905): pocketmine\Server->enablePlugin(AdvancedKits\Main object) 19.06 10:39:16 [Server] Server thread/DEBUG #11 src/pocketmine/Server(1699): pocketmine\Server->enablePlugins(integer 1) 19.06 10:39:16 [Server] Server thread/DEBUG #12 src/pocketmine/PocketMine(305): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/) 19.06 10:39:16 [Server] Server thread/DEBUG #13 /pmmp_1001_1.4.0.phar(1): require(string phar:///pmmp_1001_1.4.0.phar/src/pocketmine/PocketMine.php) 19.06 10:39:16 [Server] Server thread/INFO Disabling AdvancedKits v5.2.3

**Comment by Akuroma** [comment]
Should be fixed, if @luca28pet accepts my PR ^-^

**Comment by luca28pet** [comment]
With the latest release this should be fixed (https://poggit.pmmp.io/p/AdvancedKits/5.2.3)
Be sure to also use the latest release of PiggyCustomEnchants
