### ISSUE TITLE
inventory glitch

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [luca28pet/AdvancedKits#158]
Hello, i made a kit, that give player, enchanted armor, sword, cookies , the problem is that it make inventory glitch.... Cant wear armor, it show u wear but if u take damage armor gets unequiped ... And cant even drop items .... Maybe is because wen i claim items appear in hotbar slots? And then after some time they appear in inventory first slots ?... I use the Normal way to give kits, not hotbar replace or instant equip...

I use latest AdvancedKits and latest pmmp release ... Help :3

Ohh ya and if i die with glitched inventory i crash

**Comment by luca28pet** [comment]
Please send kits.yml

**Comment by TDMidkwhatisxd** [comment]
[kits.txt](https://github.com/luca28pet/AdvancedKits/files/2130996/kits.txt)
open it with notepad++  xd

**Comment by TDMidkwhatisxd** [comment]
was pmmp fault, it seems i dont have problems anymore
