### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by benzodoesdev** [luca28pet/AdvancedKits#159]
26.06 10:01:09 [Server] Server thread/CRITICAL Error: "Call to undefined method AdvancedKits\Main::getScheduler()" (EXCEPTION) in "AdvancedKits_dev-1.phar/src/AdvancedKits/Main" at line 54 (console) please fix as soon as possible

**Comment by benzodoesdev** [comment]
also could you add api support for ALPHA12 also, its not gonna kill anyone

**Comment by luca28pet** [comment]
That error happens because you are using an old pmmp release

**Comment by benzodoesdev** [comment]
Could you possibly add support for alpha12?

**Comment by luca28pet** [comment]
https://poggit.pmmp.io/ci/luca28pet/AdvancedKits/AdvancedKits/dev:24
This the latest dev build that works with 3.0.0-ALPHA12

**Comment by benzodoesdev** [comment]
Thanks!!!!!

**Comment by benzodoesdev** [comment]
Im receiving the same message
