### ISSUE TITLE
kit not work now

### ISSUE THREAD

**Issue by haKingdomsCraft** [luca28pet/AdvancedKits#162]
i enable ui and i click on kit is nit do anything  please help

**Comment by luca28pet** [comment]
I am not able to reproduce this. With the default configuration if you have FormAPI installed the UI works.
Please use an updated version of AdvancedKits and FormAPI, otherwise add information on how to reproduce this

**Comment by haKingdomsCraft** [comment]
U not underatand me is When i click on Kit is not do anything (UI)
