### ISSUE TITLE
plugin breaks when adding new kits =(

### ISSUE THREAD

**Issue by ShatteredAtom** [luca28pet/AdvancedKits#166]
`08.08 15:24:46 [Server] Server thread/INFO Enabling AdvancedKits v5.2.3
08.08 15:24:46 [Server] Server thread/NOTICE PiggyCustomEnchants detected. Activated custom enchants support
08.08 15:24:46 [Server] Server thread/NOTICE FormAPI detected. Activated kit selection UI support
08.08 15:24:46 [Server] Server thread/CRITICAL ErrorException: "yaml_parse_file(): scanning error encountered during parsing: could not find expected ':' (line 5, column 2), context while scanning a simple key (line 4, column 3)" (EXCEPTION) in "AdvancedKits.phar/src/AdvancedKits/Main" at line 126
08.08 15:24:46 [Server] Server thread/DEBUG #0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string yaml_parse_file(): scanning error encountered during parsing: could not find expected ':' (line 5, column 2), context while scanning a simple key (line 4, column 3), string phar:///plugins/AdvancedKits.phar/src/AdvancedKits/Main.php, integer 126, array Array())
08.08 15:24:46 [Server] Server thread/DEBUG #1 AdvancedKits.phar/src/AdvancedKits/Main(126): yaml_parse_file(string /plugins/AdvancedKits/kits.yml)
08.08 15:24:46 [Server] Server thread/DEBUG #2 AdvancedKits.phar/src/AdvancedKits/Main(45): AdvancedKits\Main->loadKits()
08.08 15:24:46 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginBase(102): AdvancedKits\Main->onEnable()
08.08 15:24:46 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/PluginManager(614): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
08.08 15:24:46 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1931): pocketmine\plugin\PluginManager->enablePlugin(AdvancedKits\Main object)
08.08 15:24:46 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1917): pocketmine\Server->enablePlugin(AdvancedKits\Main object)
08.08 15:24:46 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1711): pocketmine\Server->enablePlugins(integer 1)
08.08 15:24:46 [Server] Server thread/DEBUG #8 src/pocketmine/PocketMine(237): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
08.08 15:24:46 [Server] Server thread/DEBUG #9 /pmmp_1269_1.5.0.phar(1): require(string phar:///pmmp_1269_1.5.0.phar/src/pocketmine/PocketMine.php)
08.08 15:24:46 [Server] Server thread/INFO Disabling AdvancedKits v5.2.3`

**Comment by luca28pet** [comment]
This is likely caused by a badly formatted kits.yml
Please follow the examples and make sure you got the formatting right

**Comment by ShatteredAtom** [comment]
here is my config 
---
Yearly:
  items:
  -"diamond_block:0:32:"
 -"diamond_sword:0:1:Yearly Sword:gooey:1:poison:1:blind:1:wither:1:"
  -"diamond_axe:0:1:Yearly Axe:lumberjack:1:haste:2:"
  -"golden_apple:0:32:"
  -'steak:0:128:'
 helmet: "diamond_helmet:0:1:Yearly Helmet:enlighted:3:meditation:3:protection:10:poisoned:3:"
 chestplate: "diamond_chestplate:0:1:Yearly Chestplate:protection:10:poisoned:3:spider:3:chicken:3:"
 leggings: "diamond_leggings:0:1:Yearly Leggings:protection:10:poisoned:3:cactus:3:"
 boots: "diamond_boots:0:1:Yearly Boots:protection:10:poisoned:3:gears:3:springs:3:"
 commands:
  -"tell {player} Yearly Kit Recieved"
 cooldown:
   hours: 3360
   minutes: 0
 money: 0
...

**Comment by ShatteredAtom** [comment]
the custom enchants changed into emojis when i pasted them here

**Comment by ShatteredAtom** [comment]
due to the :'s next to them

**Comment by luca28pet** [comment]
Please send the file directly, or use pastebin so I can read it with the formatting you used and w/o emojis

**Comment by ShatteredAtom** [comment]
ok

**Comment by ShatteredAtom** [comment]
can you tell me what i did wrong

**Comment by ShatteredAtom** [comment]
?

**Comment by luca28pet** [comment]
Please do not flood.
Try with this: https://hastebin.com/iqaxeyefuh.makefile
The formatting and indentation was wrong.
Also, before reporting plugin errors please check if your configuration is a valid YAML through yamllint.com
