### ISSUE TITLE
AdvancedKit issue

### ISSUE THREAD

**Issue by Itzdvbravo** [luca28pet/AdvancedKits#173]
Ok so, in the advanced kits option, there is a option in kit.yml ->img-data: ''<- , i am trying to write Vip but in blue colour, in doesn't shows that exact thing in game, it just shows the kit name used, not in that given, i got formapi too, both formapi and advancedkits is latest and supports the pocketmine version

**Comment by luca28pet** [comment]
To change how the kit name is displayed in the form, you should change form-name and not img-data
