### ISSUE TITLE
PiggyCE enchantment not recognised on reload

### ISSUE THREAD

**Issue by Starflux** [luca28pet/AdvancedKits#176]
PiggyCE enchantment not recognised on PM reload.

however after a PM Stop Start the configuration is recognised.

This server is running PocketMine-MP 3.11.6 for Minecraft: Bedrock Edition v1.14.0 (protocol version 389)

PiggyCustomEnchants v2.1.0
AdvancedKits v5.3.0

helmet: "diamond_helmet:0:1:DEFAULT:Meditation:1"

**Comment by Starflux** [comment]
AFTER a RELOAD:
[02:37:45] [Server thread/WARNING]: [AdvancedKits] Bad configuration in kit testkit. Enchantment Meditation in item diamond_helmet:0:1:DEFAULT:Meditation:1 could not be loaded because the enchantment does not exist

after a STOP START:
[02:38:14] [Server thread/NOTICE]: [AdvancedKits] PiggyCustomEnchants detected. Activated custom enchants support

However i have now just found if i reload numerous times sometimes it finds it sometimes it doesnt. hope this helps in someway.

**Comment by minijaham** [comment]
I use numerical ID in items, and this issue does not occur on my server. You can try changing the items to all numerical ID

**Comment by minijaham** [comment]
Or downgrade your piggy custom enchants

**Comment by luca28pet** [comment]
Do not use /reload, it is terrible and will be removed in PM4
