### ISSUE TITLE
PurePerms ?

### ISSUE THREAD

**Issue by ghost** [luca28pet/AdvancedKits#178]
How do I put a kit on a grade of pureperms? I can't do it 
I did that, but it doesn't work.

Joueur:
  alias: joueur
  inheritance: []
  permissions:
  - -essentials.kit
  - -essentials.kit.other
  - -pocketmine.command.me
  - advancedkits.testkit
  - pchat.colored.format
  - pchat.colored.nametag
  - pocketmine.command.list
  - pperms.command.ppinfo

**Comment by minijaham** [comment]
Make sure both of PurePerms and AdvancedKits are loaded.

If they are, make sure that the name of the kit is all lowercase in kits.yml
Then try adding the permission
