### ISSUE TITLE
Error "Invalid argument supplied for foreach()"

### ISSUE THREAD

**Issue by Pub4Game** [luca28pet/AdvancedKits#18]
RuntimeException: "Invalid argument supplied for foreach()" (E_WARNING) in "/AdvancedKits-master/src/AdvancedKits/Main" at line 39
InvalidArgumentException: "explode() expects parameter 2 to be string, array given" (E_WARNING) in "/AdvancedKits-master/src/AdvancedKits/Kit" at line 88

// NEW

2015-10-24 [22:54:11] [Server thread/WARNING]: RuntimeException: "Invalid argument supplied for foreach()" (E_WARNING) in "/AdvancedKits_v3.1.phar/src/AdvancedKits/CoolDownTask" at line 17

**Comment by legoboy0215** [comment]
Config edit error.

**Comment by Pub4Game** [comment]
=_= I have not changed the configuration

**Comment by luca28pet** [comment]
I will fix asap

**Comment by legoboy0215** [comment]
I found a solution!

**Comment by legoboy0215** [comment]
Took me 1 hour though

**Comment by luca28pet** [comment]
Fixed now, sorry for the delay
