### ISSUE TITLE
Pureperms node?

### ISSUE THREAD

**Issue by goerick** [luca28pet/AdvancedKits#19]
For my kit name, Serf i did...

advancedkits.kitname.Serf

and

advancedkits.Serf

With no luck.

I am using pureperms 1.1.12 1.6 and pocketmine 1.6

**Comment by luca28pet** [comment]
For the kit Serf, the permission node is
advancedkits.serf

I have seen that your problem was solved on the PocketMine forums, but I'll leave an answer here for future references
