### ISSUE TITLE
Enchantments don't work.

### ISSUE THREAD

**Issue by legoboy0215** [luca28pet/AdvancedKits#23]
^^^

**Comment by luca28pet** [comment]
Did you look at the new kits.yml? https://github.com/luca28pet/AdvancedKits/blob/master/resources/kits.yml
It's pretty different from the one of the previous commits, you must change yours, too

**Comment by luca28pet** [comment]
Oh, and some enchantments are not supported on PocketMine yet, so they don't get applied to the items.
I saw that armor protection works, I tested the plugin with that

**Comment by legoboy0215** [comment]
Oh!
