### ISSUE TITLE
Enchanting Items

### ISSUE THREAD

**Issue by iDirtniverse** [luca28pet/AdvancedKits#26]
Not issues but how can I add enchantments on the items?

**Comment by legoboy0215** [comment]
I can't enchant :(

**Comment by iDirtniverse** [comment]
I saw an option in the code for enchantments but i dont know how to use them..

**Comment by luca28pet** [comment]
You can look for an example in the new kits.yml file
https://github.com/luca28pet/AdvancedKits/blob/master/resources/kits.yml
