### ISSUE TITLE
Kits giving wrong items

### ISSUE THREAD

**Issue by MrDoni98** [luca28pet/AdvancedKits#30]
[image
![lmvy2d9es2g](https://cloud.githubusercontent.com/assets/10742315/12786688/5cacd9cc-cabc-11e5-9a7e-a1dfbd0c8405.jpg)
](/http://storage3.static.itmages.ru/i/16/0203/h_1454512589_2322241_61dd23d696.jpg)
start:
  items:
    "272:0:1":
      name: "Start"
      enchantment:
        weapon_sharpness: 5
        weapon_knockback: 2
    "260:0:5":
      name: "Apples"
    "261:0:1": []
    "262:0:30": []
  helmet:
    id: 298
    name: "Start"
    enchantment:
      armor_protection: 2
  chestplate:
    id: 299
  leggings:
    id: 300
  boots:
    id: 301
  cooldown:
    hours: 24
    minutes: 30

**Comment by luca28pet** [comment]
Can you provide a readable kits.yml with proper spacing please?

**Comment by XShockinFireX** [comment]
Im having the same issue
