### ISSUE TITLE
Weird Bug

### ISSUE THREAD

**Issue by XShockinFireX** [luca28pet/AdvancedKits#37]
Every time someone gets a kit they get 99+ iron bars and some other weird stuff that isn't supposed to be there in the inventory

**Comment by XShockinFireX** [comment]
My kits.yml:

---
Archer: #Permission: advancedkits.archer
  items:
    "272:0:1": #Stone Sword
      enchantment:
        weapon_knockback: 3 #
    "260:0:5":
    "261:0:1":
    "262:0:64":
  helmet:
    id: 302 #Chainmail Helmet
    enchantment:
      armor_protection: 1 #Chainmail Chestplate Enchaned With Protection 1
  chestplate:
    id: 303
  leggings:
    id: 304
  boots:
    id: 305
  cooldown:
    hours: 0
    minutes: 0
  commands:
  - "tell {player} you got the Archer kit!"
Soldier: #Permission: advancedkits.soldier
  items:
    "267:0:1":
      enchantment:
        weapon_sharpness: 4
        weapon_knockback: 3
    "322:0:1":
      name: "A Golden Apple"
    "364:0:10":
  helmet:
    id: 306
  chestplate:
    id: 307
  leggings:
    id: 308
  boots:
    id: 309
  cooldown:
    hours: 0
    minutes: 0
  commands:
  - "tell {player} you are now a Soldier!"
V.I.P: #Permission: advancedkits.v.i.p
  items:
    "276:0:1":
      enchantment:
        weapon_sharpness: 5
        weapon_knockback: 5
    "322:1:3":
    "364:0:32":
    "258:0:1":
    "261:0:1":
      enchantment:
        flame: 5       
    "262:0:64":
  helmet:
    id: 310
  chestplate:
    id: 311
    enchantment:
     armor_protection: 5
  leggings:
    id: 312
  boots:
    id: 313
  cooldown:
    hours: 0
    minutes: 0
  commands:
  - "tell {player} you have got the V.I.P kit!"
Warrior: #Permission: advancedkits.warrior
  items:
    "267:0:1": #Iron Sword
      enchantment:
        weapon_sharpness: 4
        weapon_knockback: 4
    "322:1:1": #Golden Apple
    "364:0:32": #Steak
    "258:0:1": #Leap Axe
    "261:0:1": #Bow
      enchantment:
        flame: 5       
    "262:0:64": #Arrows
  helmet: #Iron Helmet
    id: 306
  chestplate:
    id: 307
    enchantment:
     armor_protection: 5
  leggings:
    id: 308
  boots:
    id: 309
  cooldown:
    hours: 0
    minutes: 0
  commands:
  - "tell {player} you have got the Warrior kit!"
...

**Comment by XShockinFireX** [comment]
My kits.yml:

http://pastebin.com/Sz4J3ic6

**Comment by XShockinFireX** [comment]
plz fix

**Comment by SuperCraftFacs** [comment]
Hey Shock! It's just a bug with PHP5, PHP5 doesn't support enchanting. You will have to update to PHP7 or remove the enchanted from your kits. Please close this issue.

**Comment by XShockinFireX** [comment]
Oh ok
