### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by SuperCraftFacs** [luca28pet/AdvancedKits#38]
If I want rank Player to be able to get started kit and titan to get titan kit, if I give rank Player advanced kits.command it will give them the permission to use titan kit :( Can you add it so I can do /setgperm Player advanced kits.command.starter and give titan advanedkits.command.titan.
Please add this and also please add the enchanted (the one with enchants) version to releases ;)

**Comment by luca28pet** [comment]
the permission for a kit called "name" is advancedkits.name
the permission for the command itself is advancedkits.command

**Comment by SuperCraftFacs** [comment]
Ohhhhh, I am a NOOB! Thank you if their was voting for github I vote 5 stars. Also gonna use this plugin for as long as I can.

**Comment by SuperCraftFacs** [comment]
Doesn't work, I did /setuperm NotOP36 advancedkits.name.titan
and it didn't work.

**Comment by luca28pet** [comment]
"the permission for a kit called "name" is advancedkits.name" basically means that if for example you have a kit called titan, the permission for it is advancedkits.titan

**Comment by SuperCraftFacs** [comment]
Say oh, LOL once again me a big NOOB. Thank you, still 5 stars.
