### ISSUE TITLE
YAML Parsing error

### ISSUE THREAD

**Issue by ImagicalGamer** [luca28pet/AdvancedKits#40]
Whenever I add my kits to the config it says theres an error within the plug.

**Comment by ImagicalGamer** [comment]
Here is my config:

> ---
Warrior:
  items:
    "267:0:1":
      name: "Blade"
      enchantment:
        weapon_sharpness: 2
    "320:0:25":
      name: "Food"
  helmet:
    id: 306
    name: "HelmetName"
    enchantment:
      armor_protection: 2
  chestplate:
    id: 307
    enchantment:
      armor_protection: 2
  leggings:
    id: 304
    enchantment:
      armor_protection: 2
  boots:
    id: 305
    enchantment:
      armor_protection: 2
  cooldown:
    hours: 12
  commands:
  - "tell {player} §cHere is your warrior kit, thank you for your contribution!"
Legend:
  items:
    "267:0:1":
      name: "§cLegend's_Sword"
      enchantment:
        weapon_sharpness: 3
        weapon_knockback: 1
    "320:0:25":
    "261:0:1": []
    "322:0:5":
  helmet:
    id: 306
    name: "Snapback"
    enchantment:
      armor_protection: 2
  chestplate:
    id: 311
      armor_protection: 3
  leggings:
    id: 308
      armor_protection: 3
  boots:
    id: 309
      armor_protection: 2
  cooldown:
    hours: 12
  commands:
  - "tell {player} §cHere is your Legend kit, thank you for your contribution!"
King:
  items:
    "276:0:1":
      name: "§eKing Helmet"
      enchantment:
        weapon_sharpness: 5
        weapon_knockback: 1
    "364:0:30":
    "261:0:1": []
    "322:0:5":
    "322:1:1":
      name:"§cGod_Apple"
    "388:0:1"
      name:"§aCrate_Key"
  helmet:
    id: 310
    enchantment:
      armor_protection: 3
  chestplate:
    id: 311
    enchantment:
      armor_protection: 4
  leggings:
    id: 308
    enchantment:
      armor_protection: 3
  boots:
    id: 309
    enchantment:
      armor_protection: 2
  cooldown:
    hours: 12
    minutes: 30
  commands:
  - "tell {player} §cHere is your Emporor kit, thank you for your contribution!"
emperor:
  items:
    "272:0:1":
    name: "§aCrate Key"
    "322:0:5":
    "322:1:5":
    name: "§cGod Apple"
      name: "§eEmperor's Sword"
      enchantment:
        weapon_sharpness: 5
        weapon_knockback: 2
    "320:0:30":
    "261:0:1": []
  helmet:
    id: 310
    name: "§aEmperor Helmet"
    enchantment:
      armor_protection: 3
  chestplate:
    id: 311
    name: "§cEmperor Chestplate"
    enchantment:
      armor_protection: 4
  leggings:
    id: 308
    name: "§eEmperor Helmet"
    enchantment:
      armor_protection: 3
  boots:
    id: 309
    name: "§eEmperor Boots"
    enchantment:
      armor_protection: 3
  cooldown:
    hours: 12
  commands:
  - "tell {player} §cHere is your Emperor kit, thank you for your contribution!"
god:
  items:
    "272:0:1":
      name: "§cGod Sword"
      enchantment:
        weapon_sharpness: 5
        weapon_knockback: 2
    "260:0:5":
    "261:0:1": []
    "280:0:1":
    name: "§cMagic Wand"
    enchantment:
      weapon_knockback: 10
    "388:0:2":
    name: "§aCrate Key"
    "322:0:5":
    "322:1:5":
    name: "§cGod Apple"
  helmet:
    id: 310
    name: "§cGod Helmet"
    enchantment:
      armor_protection: 4
  chestplate:
    id: 311
    name: "§cGod Chestplate"
    enchantment:
      armor_protection: 5
  leggings:
    id: 312
    name: "§cGod Leggings"
    enchantment:
      armor_protection: 4
  boots:
    id: 313
    name: "§cGod Boots"
    enchantment:
      armor_protection: 4
  cooldown:
    hours: 12
  commands:
  - "tell {player} §cYou are a god, take over this land and rule it, here is your kit, thank you for your contribution!"
​
...

**Comment by luca28pet** [comment]
Probably you edited wrongly the config
Be sure that the yaml format is right by parsing the config in a validator such as http://www.yamllint.com/

**Comment by ImagicalGamer** [comment]
Used that, even just modifying the default config and changing just the numbers had errors.

**Comment by luca28pet** [comment]
Use the official release (https://github.com/luca28pet/AdvancedKits/releases/tag/5.0) and delete the config
