### ISSUE TITLE
not an issue. just need info.

### ISSUE THREAD

**Issue by LordJoshie** [luca28pet/AdvancedKits#42]
Hey... so.... 

say I wanna give an enchanted pic with efficiency  

how do I formulate that in the yml?

**Comment by luca28pet** [comment]
`  - id: 278
    damage: 0
    count: 1
    name: "Pickaxe Name"
    enchantment:
      #name: level
      type_mining_efficiency: 1`

**Comment by LordJoshie** [comment]
thank you !! where can I get a list of all the enchant types available for
input with this plugin?

**Comment by luca28pet** [comment]
TYPE_ARMOR_PROTECTION
TYPE_ARMOR_FIRE_PROTECTION 
TYPE_ARMOR_FALL_PROTECTION
TYPE_ARMOR_EXPLOSION_PROTECTION
TYPE_ARMOR_PROJECTILE_PROTECTION
TYPE_ARMOR_THORNS
TYPE_WATER_BREATHING
TYPE_WATER_SPEED
TYPE_WATER_AFFINITY
TYPE_WEAPON_SHARPNESS
TYPE_WEAPON_SMITE
TYPE_WEAPON_ARTHROPODS
TYPE_WEAPON_KNOCKBACK
TYPE_WEAPON_FIRE_ASPECT
TYPE_WEAPON_LOOTING
TYPE_MINING_EFFICIENCY
TYPE_MINING_SILK_TOUCH
TYPE_MINING_DURABILITY
TYPE_MINING_FORTUNE
TYPE_BOW_POWER
TYPE_BOW_KNOCKBACK
TYPE_BOW_FLAME
TYPE_BOW_INFINITY
TYPE_FISHING_FORTUNE
TYPE_FISHING_LURE

**Comment by LordJoshie** [comment]
thank you very very much !! I appreciate <3
