### ISSUE TITLE
No permission & cant add kit

### ISSUE THREAD

**Issue by TonyWAV** [luca28pet/AdvancedKits#44]
Hello,
I'm having issues with the permissions and adding kits because i dont know whats the format of adding new kits and even i remove the "user and world line" & set the permission advancedkits.vip to the pureperms group and restarted my server its still saying you dont have a permission to use this kit.

please help me

**Comment by luca28pet** [comment]
The format for new kits is the one descripted in the default kits.yml (see https://github.com/luca28pet/AdvancedKits/blob/master/resources/kits.yml)
 I cannot reproduce the permissions issue:
the permission for a kit called "name" is advancedkits.name
the permission for the command itself is advancedkits.command
you can apply this to any permission manager plugin
double check

**Comment by TonyWAV** [comment]
do i need to make new kit.yml?
