### ISSUE TITLE
Give Itens Bug in GenisysPHP7

### ISSUE THREAD

**Issue by RedstoneAlmeida** [luca28pet/AdvancedKits#45]
when you receive the kit, the items have just been more kind I get basic kit, here comes it enchantment table in a pack of 99+ in the inventory, and also can not take the armor as she returns to the armor slot

**Comment by luca28pet** [comment]
Make sure you are using the latest phar and the **latest config format**

**Comment by RedstoneAlmeida** [comment]
yes
