### ISSUE TITLE
Still No permission!

### ISSUE THREAD

**Issue by TonyWAV** [luca28pet/AdvancedKits#47]
so i recently have this pureperms permissions set to group vip
![image](https://cloud.githubusercontent.com/assets/18161164/14710427/f9076840-0807-11e6-8b1b-2d084036f84b.png)
but when i get kit its still saying you haven't permission to use this kit

**Comment by luca28pet** [comment]
did you disable force-builtin-permissions?

**Comment by TonyWAV** [comment]
yes i disable but still no permission

**Comment by TonyWAV** [comment]
Please help me i really need this plugin

**Comment by luca28pet** [comment]
I have done local tests and permissions are working as they should
