### ISSUE TITLE
Um

### ISSUE THREAD

**Issue by SuperCraftFacs** [luca28pet/AdvancedKits#48]
I install the plugin and it doesn't turn on. I did not edit anything.

**Comment by XShockinFireX** [comment]
is there a console error?

**Comment by SuperCraftFacs** [comment]
idk i use old version now.

**Comment by SuperCraftFacs** [comment]
Yes, this is it: Server thread/CRITICAL]: TypeError: "Argument 3 passed to pocketmine\item\Item::get() must be of the type integer, null given, called in phar:///Users/superserver/PHP7Prison/plugins/updated.phar/src/AdvancedKits/Kit.php on line 89" (EXCEPTION) in "/src/pocketmine/item/Item" at line 1180

**Comment by luca28pet** [comment]
With the old version you have to use the old config as well
