### ISSUE TITLE
Enchants

### ISSUE THREAD

**Issue by SuperCraftFacs** [luca28pet/AdvancedKits#49]
When I put "tool_efficency: 20" it won't enchant that item with efficiency 20. Please tell me how to fix. By the way, I use old version.
Config:
---
starter:
  items:
    "267:0:1":
      enchantment:
        weapon_sharpness: 1
    "260:0:5": []
  helmet:
    id: 306
    enchantment:
      armor_protection: 1
  chestplate:
    id: 307
    enchantment:
      armor_protection: 1
  leggings:
    id: 308
    enchantment:
      armor_protection: 1
  boots:
    id: 309
    enchantment:
      armor_protection: 1
  cooldown:
    hours: 0
    minutes: 15
jack:
  items:
    "276:0:1":
      enchantment:
        weapon_sharpness: 2
    "322:0:5": []
  helmet:
    id: 310
    enchantment:
      armor_protection: 2
  chestplate:
    id: 311
    enchantment:
      armor_protection: 2
  leggings:
    id: 312
    enchantment:
      armor_protection: 2
  boots:
    id: 313
    enchantment:
      armor_protection: 2
  cooldown:
    hours: 0
    minutes: 15
queen:
  items:
    "276:0:1":
      enchantment:
        weapon_sharpness: 4
    "322:0:10": []
    "466:0:5": []
  helmet:
    id: 310
    enchantment:
      armor_protection: 4
  chestplate:
    id: 311
    enchantment:
      armor_protection: 4
  leggings:
    id: 312
    enchantment:
      armor_protection: 4
  boots:
    id: 313
    enchantment:
      armor_protection: 4
  cooldown:
    hours: 0
    minutes: 10
king:
  items:
    "276:0:1":
      enchantment:
        weapon_sharpness: 6
    "322:0:10": []
    "466:0:5": []
    "438:22:3": []
    "438:33:2": []
  helmet:
    id: 310
    enchantment:
      armor_protection: 6
  chestplate:
    id: 311
    enchantment:
      armor_protection: 6
  leggings:
    id: 312
    enchantment:
      armor_protection: 6
  boots:
    id: 313
    enchantment:
      armor_protection: 6
  cooldown:
    hours: 0
    minutes: 5
ace:
  items:
    "276:0:1":
      enchantment:
        weapon_sharpness: 10
    "322:0:64": []
    "466:0:32": []
    "438:22:10": []
    "438:33:10": []
  helmet:
    id: 310
    enchantment:
      armor_protection: 10
  chestplate:
    id: 311
    enchantment:
      armor_protection: 10
  leggings:
    id: 312
    enchantment:
      armor_protection: 10
  boots:
    id: 313
    enchantment:
      armor_protection: 10
  cooldown:
    hours: 0
    minutes: 2
staff:
  items:
    "276:0:1":
      enchantment:
        weapon_sharpness: 10
    "322:0:64": []
    "466:0:64": []
    "438:22:20": []
    "438:33:120": []
  helmet:
    id: 310
    enchantment:
      armor_protection: 10
  chestplate:
    id: 311
    enchantment:
      armor_protection: 10
  leggings:
    id: 312
    enchantment:
      armor_protection: 10
  boots:
    id: 313
    enchantment:
      armor_protection: 10
  cooldown:
    hours: 0
    minutes: 5
super:
  items:
    "276:0:1":
      enchantment:
        weapon_sharpness: 15
    "322:0:64": []
    "466:0:64": []
    "438:22:20": []
    "438:33:20": []
  helmet:
    id: 310
    enchantment:
      armor_protection: 15
  chestplate:
    id: 311
    enchantment:
      armor_protection: 15
  leggings:
    id: 312
    enchantment:
      armor_protection: 15
  boots:
    id: 313
    enchantment:
      armor_protection: 15
  cooldown:
    hours: 168
    minutes: 0
tools:
  items:
    "278:0:1":
      enchantment:
        15: 1
    "278:0:1":
      enchantment:
        15: 1
    "277:0:1":
      enchantment:
        15: 1
  cooldown:
    hours: 0
    minutes: 30
yt:
  items:
    "276:0:1":
      enchantment:
        weapon_sharpness: 2
    "322:0:5": []
  helmet:
    id: 310
    enchantment:
      armor_protection: 2
  chestplate:
    id: 311
    enchantment:
      armor_protection: 2
  leggings:
    id: 312
    enchantment:
      armor_protection: 2
  boots:
    id: 313
    enchantment:
      armor_protection: 2
  cooldown:
    hours: 0
    minutes: 2
ytplus:
  items:
    "276:0:1":
      enchantment:
        weapon_sharpness: 4
    "322:0:10": []
    "466:0:5": []
  helmet:
    id: 310
    enchantment:
      armor_protection: 4
  chestplate:
    id: 311
    enchantment:
      armor_protection: 4
  leggings:
    id: 312
    enchantment:
      armor_protection: 4
  boots:
    id: 313
    enchantment:
      armor_protection: 4
  cooldown:
    hours: 0
    minutes: 10
...

**Comment by luca28pet** [comment]
You  have to use new version for enchants to work
