### ISSUE TITLE
Time limit 

### ISSUE THREAD

**Issue by qwefqwfqwefqwef** [luca28pet/AdvancedKits#5]
Can add a time limit? seconds, minutes, hours, days

**Comment by luca28pet** [comment]
Download version 2.2: https://github.com/luca28pet/AdvancedKits/releases/tag/2.2
It has time limit

**Comment by qwefqwfqwefqwef** [comment]
Uh.... I suggested another time limit

**Comment by qwefqwfqwefqwef** [comment]
@luca28pet Where's the TIME limit? I offered to make seconds,minutes,hours,days! And not this nonsense!

**Comment by luca28pet** [comment]
Look at cooldown feature. In a kit set:
cooldown: numberofminutes
