### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by XShockinFireX** [luca28pet/AdvancedKits#50]
Can you add an option to buy a kit once and use that kit forever?

**Comment by luca28pet** [comment]
With forever you mean until a player dies ?

**Comment by legoboy0215** [comment]
No, until you manually remove the player.

**Comment by luca28pet** [comment]
I will try to add this in the next version

**Comment by mcpedudes** [comment]
cant use the kits they dont come out off your inventory fix that

**Comment by XShockinFireX** [comment]
@luca28pet ok
