### ISSUE TITLE
Question about adding certain items

### ISSUE THREAD

**Issue by corytortoise** [luca28pet/AdvancedKits#51]
I apologize if this has already been asked or shouldn't be asked, but how do I add items in kits.yml that have the IDs with colons? For example, I want to add an Enchanted Golden Apple that has the ID of 322:1. This doesn't seem to work, which makes sense. Is there a way to add these items? If so, what is the correct format? Thanks in advance.

**Comment by luca28pet** [comment]
this is the format:

- id: 322
  damage: 1
  count: 1

322 is the id, 1 or whatever after the colons is the damage
