### ISSUE TITLE
Inventory Error

### ISSUE THREAD

**Issue by KennanFatt** [luca28pet/AdvancedKits#54]
Getting the kits, and cant choose or hold some item on inventory..

**Comment by corytortoise** [comment]
My guess is that it haa to do with those specific items. Can those items be held when a player obtains them through /give?

**Comment by luca28pet** [comment]
I'm going to update the plugin soon to remove those messy bugs in v 5.0
Especially that it gives you wrong/invalid items in some cases
Stay tuned

**Comment by luca28pet** [comment]
It turns out that i had to delete my playername.dat file to fix the issue of wrong/invalid given items
I worked on 5.1 too, it is going to be released later today or tomorrow
