### ISSUE TITLE
Suggestion #2

### ISSUE THREAD

**Issue by XShockinFireX** [luca28pet/AdvancedKits#55]
A nice feature that would be cool to have is if there is a color option for kits with leather armor.

**Comment by corytortoise** [comment]
Is dyed armor even supported by any PM forks at the moment?

**Comment by luca28pet** [comment]
At the moment colored armour isn't supported by any Pocketmine fork I'm going to close this for now

**Comment by legoboy0215** [comment]
It is supported by Genisys...
