### ISSUE TITLE
No kits .

### ISSUE THREAD

**Issue by trapxbashh** [luca28pet/AdvancedKits#58]
When I do /Kit , it just says available kits . And nothing under it , I checked my permmions everything's right and my formats right too . I am using genysis 0.15.0 if that's matters .

**Comment by luca28pet** [comment]
Which version are you using? what is your kits.yml?

**Comment by trapxbashh** [comment]
I'm using (Version: 4.0.1 for 1.5 API 1.12.0)
Here's my yml :
---
start:
  items:
  - "311:0:1:DEFAULT:armor_protection:1"
  - "260:0:5"
  helmet: 298
  chestplate: 299
  leggings: 300
  boots: 301
  cooldown:
    hours: 24
    minutes: 30
  commands:
  - "tell {player} you got an awesome kit thanks to AdvancedKits plugin
  worlds:
  - "world"
basicbuilder:
  items:
  - "4:0:25"
  - "275:0:1"
  - "297:0:3"
  chestplate: 299
  money: 20
  cooldown:
    minutes: 2
  users:
  - "luca28pet"
  - "dioconsole"
  - "trapxbashh"
...

**Comment by trapxbashh** [comment]
Ignore the dots , idk why it's showing up like that 😂

**Comment by trapxbashh** [comment]
Can I email it to you ? , that's not how my kits.yml file likes at all !

**Comment by luca28pet** [comment]
You can paste it to pastebin.com and send me the link.
First of all try upgrading to v5.1 (you don't need to change anything in the config) (link: https://github.com/luca28pet/AdvancedKits/releases/tag/5.1). Let me know if that works.

**Comment by trapxbashh** [comment]
Okay the new version works , thanks .
