### ISSUE TITLE
i cant use /kit guest {username}

### ISSUE THREAD

**Issue by FuxonPlayz** [luca28pet/AdvancedKits#60]
Hi There i cant give anyone kit using /kit guest {username} and i cant add 2nd kit

**Comment by trapxbashh** [comment]
Same with me , I can't add a 2nd Kit ):

**Comment by luca28pet** [comment]
@FuxonPlayz i will add that command feature in the next update. Can you show me your kits.yml? (pastebin.com)

**Comment by FuxonPlayz** [comment]
@luca28pet never mind i fixed the Problem I just removed --- in the 2nd kit and i but ... At the end and its worked!
