### ISSUE TITLE
Kits.yml Problems

### ISSUE THREAD

**Issue by trapxbashh** [luca28pet/AdvancedKits#61]
I always have trouble adding kits , I think my format my be off but I copy and pasted the kits and used the same format but it doesn't seem to work ... Can u take a look for me :
http://pastebin.com/AcrQaGKr
Also is there an app or something that correct the errors I am having ?

**Comment by trapxbashh** [comment]
may*

**Comment by legoboy0215** [comment]
@trapxbashh yamllint.com

**Comment by luca28pet** [comment]
Errors i've seen:
lines 44, 69, 72, 95, 96: there is a closing ", but you forgot to open one
lines 67, 93: there are some spaces before the kit name (there should not be any)
To avoid this errors you can try using some program like Notepad++ for editing .yml files

**Comment by trapxbashh** [comment]
@legoboy0215 thanks it worked , but it's still only showing 2 kits when I do /Kit even though I put more than 2 in the YML

**Comment by trapxbashh** [comment]
@luca28pet ok I will check

**Comment by trapxbashh** [comment]
It worked thanks
