### ISSUE TITLE
In Need Of An Helper !

### ISSUE THREAD

**Issue by trapxbashh** [luca28pet/AdvancedKits#62]
Hello , first off this is not an ISSUE ! This is an request , sorry for uploading this under issues in advance ): . Well back to what I was saying ... I need someone to help me make my kits , I have trouble configuring this plugin bc of it's weird format . I just need you to configure 7 basic kits , nothing complicated there just rank kits that consists of armor and a sword and a pickaxe.

**Comment by trapxbashh** [comment]
http://pastebin.com/rhWDvN5

**Comment by trapxbashh** [comment]
* UPDATE * if anyone can check my kits file to see if it's correct that be great ! http://pastebin.com/6teU91Tz

**Comment by AndroidHackPro** [comment]
Work fine because I used xD Here is my server 

Servidor:
IP: 104.36.85.3
PUERTO: 26417

**Comment by trapxbashh** [comment]
I got it down nvm fixed for me but still got some more problems

**Comment by AndroidHackPro** [comment]
Here is! 

https://github.com/AndroidHackPro/AdvancedKits-Espa-ol/blob/master/resources/kits.yml

I'm copy the github for Spanish translation and some issues in your kit code. You need keep save the two (2) firsts space
