### ISSUE TITLE
Minor Errors.

### ISSUE THREAD

**Issue by trapxbashh** [luca28pet/AdvancedKits#64]
Okay I got some errors with my config that I can't find , I found most of them bc most of the kits work but 1 dosent ( Poseidon ) and in breaking dosent show up on any of the kits . Here's the pastebin : http://pastebin.com/TcPi7JZX

**Comment by trapxbashh** [comment]
unbreaking enchant dosent show *

**Comment by luca28pet** [comment]
You didn't specifythe enchantment level

**Comment by trapxbashh** [comment]
Where ? After all enchantments I have a number that is the enchantment lvl , and what about th poolside kit not working ?

**Comment by trapxbashh** [comment]
Poseidon Kit not working*
