### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by JoRa22** [luca28pet/AdvancedKits#65]
Hi All,
When I attempt to run the kit I receive an unknown error displayed in the chat in game (gives the items anyway). On the console i get an error, see below. What is causing the issue and how can I Fix it?

0:18:10 [Server] Server thread/INFO [Guest] Panda_Charm > We need more ppl <_>
18.07 20:18:10 [Server] Server thread/CRITICAL TypeError: "Argument 1 passed to AdvancedKits\Kit::loadItem() must be of the type integer, string given, called in /plugins/AdvancedKits-master/src/AdvancedKits/Kit.php on line 73" (EXCEPTION) in "/AdvancedKits-master/src/AdvancedKits/Kit" at line 98
18.07 20:18:10 [Server] Server thread/CRITICAL Unhandled exception executing command 'kit voter' in kit: Argument 1 passed to AdvancedKits\Kit::loadItem() must be of the type integer, string given, called in /plugins/AdvancedKits-master/src/AdvancedKits/Kit.php on line 73

Thank you,
JoRa22

**Comment by RedstoneAlmeida** [comment]
Cool

**Comment by luca28pet** [comment]
Probably a bad kit.yml configuration. Check that you use **correct numeric** ids
