### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by iPeedroPvP** [luca28pet/AdvancedKits#69]
what add in recent update?

**Comment by luca28pet** [comment]
What update?
If you mean the latest commit, I just fixed a bug where effect amplifier wouldn't get applied
If you mean the latest release (5.1), I changed the config format and fixed some bugs

**Comment by iPeedroPvP** [comment]
ok thx

**Comment by r0m4ng5r** [comment]
How i can this Plugin with Economy? :/ ..

**Comment by r0m4ng5r** [comment]
How can I use this Pligin with Economy ?! :/***

Fail ^^
