### ISSUE TITLE
bug with permissions

### ISSUE THREAD

**Issue by Pub4Game** [luca28pet/AdvancedKits#7]
![fdo8atv2tig](https://cloud.githubusercontent.com/assets/11244874/9023533/54ce8d14-38a8-11e5-9c10-5cad0d69c75e.jpg)

i op,can't use /kit basicpvp

**Comment by luca28pet** [comment]
Use PurePerms to give yourself the permission advancedkits.basicpvp
If you haven't PurePerms and don't want to install it you will need to wait untill version 3.0 is released

**Comment by Pub4Game** [comment]
Well, thank you) Add bypass time

**Comment by Pub4Game** [comment]
@luca28pet  I'm OP and I still can't use a kit Version 3.0,

**Comment by luca28pet** [comment]
Can you post kits.yml and ranks.yml please ?
Are you using PurePerms ?

**Comment by Pub4Game** [comment]
No, in the test I did not use PurePerms

No configurations, no, it used standard

**Comment by luca28pet** [comment]
You are not able to get basicpvp because probably you are using default configuration.
In kits.yml, under basicpvp, there is a parameter called worlds, edit it as you need or delete it if you want the kit to be available in all worlds

**Comment by Pub4Game** [comment]
Exactly, I should have paid attention to him, thank you!
