### ISSUE TITLE
Help please 

### ISSUE THREAD

**Issue by GamingGapple** [luca28pet/AdvancedKits#72]
When every I try doing item->addEnchantment($ench->setLevel($name_level)); or 267:0:1:Default :weapon_sharpness:3:weapon_knockback they never work please please help me

**Comment by iPeedroPvP** [comment]
267:0:1:Default :weapon_sharpness:3:weapon_knockback:1"

**Comment by GamingGapple** [comment]
That won't work

**Comment by oGalatico** [comment]
as I do to delight picks and axes, when I try in the game does not appear incantations

**Comment by SinlesFlyer376** [comment]
I'm having problems with ench1_name:ench1_level:ench2_name:ench2_level" I keep doing stuff like
"313:0:1:Elite:ench1_protection:ench1_3:ench2_unbreaking:ench2_3"

**Comment by luca28pet** [comment]
ench1_protection doesn't exist.
This is the list of the usable enchantments:
ARMOR_PROTECTION
ARMOR_FIRE_PROTECTION
ARMOR_FALL_PROTECTION
ARMOR_EXPLOSION_PROTECTION
ARMOR_PROJECTILE_PROTECTION
ARMOR_THORNS
WATER_BREATHING
WATER_SPEED
WATER_AFFINITY
WEAPON_SHARPNESS
WEAPON_SMITE
WEAPON_ARTHROPODS
WEAPON_KNOCKBACK
WEAPON_FIRE_ASPECT
WEAPON_LOOTING
MINING_EFFICIENCY
MINING_SILK_TOUCH
MINING_DURABILITY
MINING_FORTUNE
BOW_POWER
BOW_KNOCKBACK
BOW_FLAME
BOW_INFINITY
FISHING_FORTUNE
FISHING_LURE
(From https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/item/enchantment/Enchantment.php#L29)
