### ISSUE TITLE
PurePerms permission nodes help

### ISSUE THREAD

**Issue by Jorti1** [luca28pet/AdvancedKits#75]
I have set my nodes with the info provided....
  - advancedkits.{kit name} 

I tried to see if it works and it doesn't, I already added permission exactly how to rank is written and all in lowercase. Does it only work for each person or per group also?

I am doing it per group.

Also, does the permission work if I add a parent, will the parent also get the permission?

**Comment by luca28pet** [comment]
You can do it individually or per group
