### ISSUE TITLE
Enchantments doing 2 enchants

### ISSUE THREAD

**Issue by SinlesFlyer376** [luca28pet/AdvancedKits#76]
"313:0:1:Elite:ench1_protection:ench1_3:ench2_unbreaking:ench2_3"
ench1_name:ench1_level:ench2_name:ench2_level"
I'm so confused could someone help me?

**Comment by luca28pet** [comment]
Example
"313:0:1:Name:weapon_sharpness:1:weapon_knockback:1"

This is the list of the usable enchantments:
ARMOR_PROTECTION
ARMOR_FIRE_PROTECTION
ARMOR_FALL_PROTECTION
ARMOR_EXPLOSION_PROTECTION
ARMOR_PROJECTILE_PROTECTION
ARMOR_THORNS
WATER_BREATHING
WATER_SPEED
WATER_AFFINITY
WEAPON_SHARPNESS
WEAPON_SMITE
WEAPON_ARTHROPODS
WEAPON_KNOCKBACK
WEAPON_FIRE_ASPECT
WEAPON_LOOTING
MINING_EFFICIENCY
MINING_SILK_TOUCH
MINING_DURABILITY
MINING_FORTUNE
BOW_POWER
BOW_KNOCKBACK
BOW_FLAME
BOW_INFINITY
FISHING_FORTUNE
FISHING_LURE
(From https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/item/enchantment/Enchantment.php#L29)

**Comment by SinlesFlyer376** [comment]
Thank you

**Comment by SinlesFlyer376** [comment]
How could I get custom enchants implemented into this? I have the plugin but I wouldn't know how to implement it in
