### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by NycuRO** [luca28pet/AdvancedKits#77]
Hello. What enchantments name uses pickaxe?

E.g. NAME:pickaxe_unbreaking:3 not work @luca28pet

**Comment by iPeedroPvP** [comment]
mining_durability
mining_efficency

**Comment by NycuRO** [comment]
@iPeedroPvP And for sword : bane of artropods and fire aspect?

**Comment by luca28pet** [comment]
This is the list of the usable enchantments:
ARMOR_PROTECTION
ARMOR_FIRE_PROTECTION
ARMOR_FALL_PROTECTION
ARMOR_EXPLOSION_PROTECTION
ARMOR_PROJECTILE_PROTECTION
ARMOR_THORNS
WATER_BREATHING
WATER_SPEED
WATER_AFFINITY
WEAPON_SHARPNESS
WEAPON_SMITE
WEAPON_ARTHROPODS
WEAPON_KNOCKBACK
WEAPON_FIRE_ASPECT
WEAPON_LOOTING
MINING_EFFICIENCY
MINING_SILK_TOUCH
MINING_DURABILITY
MINING_FORTUNE
BOW_POWER
BOW_KNOCKBACK
BOW_FLAME
BOW_INFINITY
FISHING_FORTUNE
FISHING_LURE
(From https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/item/enchantment/Enchantment.php#L29)
