### ISSUE TITLE
Fix please 

### ISSUE THREAD

**Issue by GamingGapple** [luca28pet/AdvancedKits#80]
Server thread/CRITICAL Error: "Call to undefined method pocketmine\item\enchantment\Enchantment::getEffectByName()" (EXCEPTION) in "/phar_AdvancedKits-master_66HLZLngRYAt5Gt.phar/src/AdvancedKits/Kit" at line 105
06.10 23:36:26 [Server] Server thread/CRITICAL Unhandled exception executing command 'kit testkit' in kit: Call to undefined method pocketmine\item\enchantment\Enchantment::getEffectByName()

**Comment by EnderKenji** [comment]
Yeh got same issue^

**Comment by GamingGapple** [comment]
That didn't work it made the plugin stop working

**Comment by ItzRadius** [comment]
@GamingGapple i'll do a pull request and we'll try get it fixed asap. it's only a little change.
