### ISSUE TITLE
0.16 bug? 

### ISSUE THREAD

**Issue by Xelcronia** [luca28pet/AdvancedKits#84]
So, I setup a few kits and set up signs, kits having armour and a few other stuff. But at times when players tap on the signs, they get only a golden apple. The rest get omitted, needing a server reboot. 

Using latest master
OS: Ubuntu 15 64bit
Software: Genisys 0.16
php: 7.0.4

**Comment by GamingGapple** [comment]
I'm 99.9% sure Genisys is not 0.16

**Comment by XShockinFireX** [comment]
@GamingGapple There is a 0.16 Genisys branch, so yes, Genisys also supports 0.16.

**Comment by Xelcronia** [comment]
Kits don't work for players anymore. Gives No Permission message even when perks are set. Only works for ops :(
@GamingGapple  https://github.com/iTXTech/Genisys/tree/0.16

**Comment by GamingGapple** [comment]
But it's in beta wait for it to fully release https://github.com/iTXTech/Genisys

**Comment by Xelcronia** [comment]
Even if it Genisys releases, Advanced Kits won't work unless its updated.

**Comment by SuperDude36** [comment]
Kits work fine for me.
[AdvancedKits_v5.0.phar.zip](https://github.com/luca28pet/AdvancedKits/files/572545/AdvancedKits_v5.0.phar.zip)

**Comment by Xelcronia** [comment]
@SuperDude36  Have you tried it with PurePerms?

**Comment by SuperDude36** [comment]
Yeah

**Comment by SuperDude36** [comment]
Did you set the perm right? For Steve to to get kit starter it's "/setuperm Steve advanced kits.starter"

**Comment by SuperDude36** [comment]
wait no, it's "/setuperm Steve advancedkits.starter"

**Comment by Xelcronia** [comment]
@SuperDude36 Do I have to set perms for every player myself?

**Comment by SuperDude36** [comment]
No, you could do "/setgperm VIP advancedkits.vip"

**Comment by SuperDude36** [comment]
@Xelcronia Don't give your players advancedkits.admin because they could do /akreload That reloads your kits.yml So if you working on something and experimenting with like sharpness 100 and a player gets that kit, then that would be bad.

**Comment by Xelcronia** [comment]
Alright. Lemme test it out.

**Comment by inferboy** [comment]
bug, some players can't do /kit in game

**Comment by inferboy** [comment]
permissions are fine

**Comment by Xelcronia** [comment]
Yeah, I've got the permissions working thanks to @SuperDude36. The only 2 problems now are, first being some players report they can't use the /kit command and some players do not get the whole kit (out of 10 items, they get only 1)

**Comment by inferboy** [comment]
i confirm the /kit command issue, some players can't use it

**Comment by SuperDude36** [comment]
Sometimes some commands just don't work. I turned my server on and played on it, warps didn't work. I restarted it, and BAM! They work now...

**Comment by TDMidkwhatisxd** [comment]
How doi use economy? No options

**Comment by Xelcronia** [comment]
https://github.com/luca28pet/AdvancedKits/issues/78

**Comment by luca28pet** [comment]
Is this issue still happening?

**Comment by GamingGapple** [comment]
No it works fine for me
