### ISSUE TITLE
kit permission

### ISSUE THREAD

**Issue by patrycy004** [luca28pet/AdvancedKits#85]
hey i have question? how can i give permission my kit i dont want normal player can take kit only vip how can i set this?

**Comment by GamingGapple** [comment]
Are you use pureperms

**Comment by patrycy004** [comment]
yeah

**Comment by GamingGapple** [comment]
Okay so this is the perm I use for my vip rank 

  - advancedkits.VIP

Make you have two spaces before the -

**Comment by patrycy004** [comment]
but i must write this in  plugin yml or what?? XD you know give me instruction in steps srry im BIG noob

**Comment by GamingGapple** [comment]
You go to your server plugin files and find pureperm groups and put the command in with the group you want

**Comment by GamingGapple** [comment]
Just like this
![img_0045](https://cloud.githubusercontent.com/assets/21264258/20564074/5250ccc0-b140-11e6-9df8-d7443f2531b9.PNG)

**Comment by patrycy004** [comment]
holy freaking banana THANK YOU

**Comment by GamingGapple** [comment]
You're welcome
