### ISSUE TITLE
items not appearing 

### ISSUE THREAD

**Issue by mote166** [luca28pet/AdvancedKits#87]
sometimes when anyone tries to get a kit he gets like half of them . and he has to punch a block to get the rest of the items . and sometimes the envintory gets empty and the player can't see that hes wearing an armor while he is actually wearing it .

**Comment by luca28pet** [comment]
Do not use custom names if you do not want this kind of problems

**Comment by mote166** [comment]
what do you mean by custom names ? im using english letters only

**Comment by mote166** [comment]
@luca28pet
