### ISSUE TITLE
efficiency and durability enchant for armors, and weapons?

### ISSUE THREAD

**Issue by andris155** [luca28pet/AdvancedKits#89]

**Comment by luca28pet** [comment]
Example
"313:0:1:Name:weapon_sharpness:1:weapon_knockback:1"

This is the list of the usable enchantments:
ARMOR_PROTECTION
ARMOR_FIRE_PROTECTION
ARMOR_FALL_PROTECTION
ARMOR_EXPLOSION_PROTECTION
ARMOR_PROJECTILE_PROTECTION
ARMOR_THORNS
WATER_BREATHING
WATER_SPEED
WATER_AFFINITY
WEAPON_SHARPNESS
WEAPON_SMITE
WEAPON_ARTHROPODS
WEAPON_KNOCKBACK
WEAPON_FIRE_ASPECT
WEAPON_LOOTING
MINING_EFFICIENCY
MINING_SILK_TOUCH
MINING_DURABILITY
MINING_FORTUNE
BOW_POWER
BOW_KNOCKBACK
BOW_FLAME
BOW_INFINITY
FISHING_FORTUNE
FISHING_LURE
(From https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/item/enchantment/Enchantment.php#L29)

**Comment by andris155** [comment]
I didn't find WEAPON_DURABILITY, and WEAPON_EFFICIENCY.
Use MINING_DURABILITY, and MINING_EFFICIENCY? Works this enchants on weapons or armors?
