### ISSUE TITLE
Bug and defect

### ISSUE THREAD

**Issue by Pub4Game** [luca28pet/AdvancedKits#9]
Fatal error: Call to a member function reduceMoney() on boolean in C:\PocketMine-MP\plugins\AdvancedKits_v3\src\AdvancedKits\EconomyManager.php on line 30

please fix
defect

                if(isset($this->kits[strtolower($args[0])]["money"])){
                    if($this->economy->grantKit($sender, (int) $this->kits[strtolower($args[0])]["money"])){
                        $this->addKit(strtolower($args[0]), $sender);
                        $sender->sendMessage("Selected kit: ".$args[0].". Taken ".$this->kits[strtolower($args[0])]["money"]." money");
                    }else{
                        $sender->sendMessage("You can not afford this kit");
                    }
                }else{
                    $this->addKit(strtolower($args[0]), $sender);
                    $sender->sendMessage("Selected kit: ".$args[0]);
                }

Add file_put_contents($this->getDataFolder()."cooldowns.sl", serialize($this->coolDown));

                if(isset($this->kits[strtolower($args[0])]["money"])){
                    if($this->economy->grantKit($sender, (int) $this->kits[strtolower($args[0])]["money"])){
                        $this->addKit(strtolower($args[0]), $sender);
                         $sender->sendMessage("Selected kit: ".$args[0].". Taken ".$this->kits[strtolower($args[0])]["money"]." money");
						file_put_contents($this->getDataFolder()."cooldowns.sl", serialize($this->coolDown));
                    }else{
                        $sender->sendMessage("You can not afford this kit");
                    }
                }else{
                    $this->addKit(strtolower($args[0]), $sender);
                    $sender->sendMessage("Selected kit: ".$args[0]);
					file_put_contents($this->getDataFolder()."cooldowns.sl", serialize($this->coolDown));
                }

**Comment by luca28pet** [comment]
A fix will be released soon

**Comment by Pub4Game** [comment]
@luca28pet Why You not added -  file_put_contents($this->getDataFolder()."cooldowns.sl", serialize($this->coolDown));
After all, if the server will be shut incorrect,then the coolDown will not be saved

**Comment by luca28pet** [comment]
Most of the times onDisable gets called anyway
