### ISSUE TITLE
Adding cost

### ISSUE THREAD

**Issue by MSG100TC** [luca28pet/AdvancedKits#94]
How to add cost to the kits? Can you give me an example? Thanks!

**Comment by diygun** [comment]
Of course 
eg of kits.yml
start
---
pvp:
  items:
  - "298:0:1"
  - "299:0:1"
  - "300:0:1"
  - "301:0:1"
  - "272:0:1"
  - "260:0:3"
  money: 75
...
end
money are the cost for "get" the kit and you need an economy plugins , if you want you can add other kits like this :
---
pvp:
  items:
  - "298:0:1"
  - "299:0:1"
  - "300:0:1"
  - "301:0:1"
  - "272:0:1"
  - "260:0:3"
  money: 75
assasin:
  items:
  - "306:0:1"
  - "307:0:1"
  - "308:0:1"
  - "309:0:1"
  - "357:0:1"
  - "276:0:1"
  - "364:0:10"
  money: 10000
barbar:
  items:
  - "306:0:1"
  - "311:0:1"
  - "308:0:1"
  - "309:0:1"
  - "279:0:1"
  - "364:0:10"
  - "257:0:1"
  - "365:0:1"
  money: 15000
sniper:
  items:
  - "306:0:1"
  - "307:0:1"
  - "308:0:1"
  - "309:0:1"
  - "261:0:1"
  - "262:0:64"
  - "363:0:1"
  - "364:0:10"
  money: 15000
bassicpvp:
  items:
  - "302:0:1"
  - "307:0:1"
  - "304:0:1"
  - "305:0:1"
  - "267:0:1"
  - "364:0:10"
  money: 2500
...
(eg of my server s kit )
I hope I help U
sorry for my English im French :S

**Comment by MSG100TC** [comment]
Thanks! You helped me a lot.

What about the Splash potions? How to add them? PigRaid has them tho xD

**Comment by diygun** [comment]
You can use ItemEffect for add effect to potions item.
Or change your version to https://github.com/TesseractTeam/Tesseract
