### ISSUE TITLE
Enchantments in text

### ISSUE THREAD

**Issue by Ishannaik** [luca28pet/AdvancedKits#95]
Hey can u list the enchantments so i can add some other enchantments to my bow
eg if i used 
  - "261:0:1"
 - "267:0:1:Legend bow:weapon_punch:2:weapon_infinity:1"
the bow is shining but has no enchants on it

**Comment by Ishannaik** [comment]
can you list the enchant ments in text so i can add them to my armor and my weapons?

**Comment by diygun** [comment]
Hi
Hier you can find all http://www.minecraftforum.net/forums/minecraft-discussion/creative-mode/365638-enchantment-id-list
And for add enchants to armor you need replace weapon with armor .

**Comment by luca28pet** [comment]
Ser #89 for a list of enchantments
