### ISSUE TITLE
How to add kits?

### ISSUE THREAD

**Issue by MSG100TC** [luca28pet/AdvancedKits#96]
Can someone give me a correct format for adding kits? Because mine does not work somehow. It shows the "testkit" only even I reloaded the server.

---
testkit:
  # Fromat: "id:damage:count:name:ench_name:ench_level"

  # If you want ONLY custom name (no enchantments): "id:damage:count:name"

  # If you don't want enchantments or custom name: "id:damage:count"

  # If you want ONLY enchantments (no custom name): "id:damage:count:DEFAULT:ench_name:ench_level" -- you have to put DEFAULT in the name field

  # If you want more than one enchantment just do: "id:damage:count:name:ench1_name:ench1_level:ench2_name:ench2_level"
  # or "id:damage:count:DEFAULT:ench1_name:ench1_level:ench2_name:ench2_level" if you don't want a custom item name

  # Please note: You have to write numeric IDs
  items:
  - "260:0:10"
  - "267:0:1:Sword Name:weapon_sharpness:3:weapon_knockback:1"
  helmet: "302:0:1"
  chestplate: "303:0:1:DEFAULT:armor_protection:1"
  leggings: "304:0:1:Leggings Name"
  boots: "305:0:1"
  money: 75
  commands:
  - "tell {player} You've selected the testkit!"

  cooldown:
    hours: 0
    minutes: 0

  # Format: "name:time:amplifier"
  # Time is in seconds
  effects:
  - "speed:120:2"

  # If you do not use pureperms, use 'worlds' to specify in which worlds you want this kit to be used
  worlds:
  - "kitpvp"
  # If you do not use pureperms, use 'users' to specify which players will be able to get this kit
  users:
  - "luca28pet"
  - "dioconsole"
  fighter:
  # Fromat: "id:damage:count:name:ench_name:ench_level"

  # If you want ONLY custom name (no enchantments): "id:damage:count:name"

  # If you don't want enchantments or custom name: "id:damage:count"

  # If you want ONLY enchantments (no custom name): "id:damage:count:DEFAULT:ench_name:ench_level" -- you have to put DEFAULT in the name field

  # If you want more than one enchantment just do: "id:damage:count:name:ench1_name:ench1_level:ench2_name:ench2_level"
  # or "id:damage:count:DEFAULT:ench1_name:ench1_level:ench2_name:ench2_level" if you don't want a custom item name

  # Please note: You have to write numeric IDs
  items:
  - "260:0:10"
  - "267:0:1:Sword Name:weapon_sharpness:3:weapon_knockback:1"
  helmet: "302:0:1"
  chestplate: "303:0:1:DEFAULT:armor_protection:1"
  leggings: "304:0:1:Leggings Name"
  boots: "305:0:1"
  money: 75
  commands:
  - "tell {player} You've selected the testkit!"

  cooldown:
    hours: 0
    minutes: 0

  # Format: "name:time:amplifier"
  # Time is in seconds
  effects:
  - "speed:120:2"

  # If you do not use pureperms, use 'worlds' to specify in which worlds you want this kit to be used
  worlds:
  - "kitpvp"
  # If you do not use pureperms, use 'users' to specify which players will be able to get this kit
  users:
  - "luca28pet"
  - "dioconsole"
  
...

I even copy and pasted the example config above, but it still only shows the testkit. How to fix this? Can someone give me a correct format/examples for adding kits? Thanks!

**Comment by diygun** [comment]
You can start with this example 
Name_of_plugins:
  items:
  -"ID:damage:amount"
  -again if you want other item
  money:
(you can add more options if you see testkit)

**Comment by MSG100TC** [comment]
Are splash potions working?

**Comment by diygun** [comment]
If your PocketMine-MP.phar or other mcpe api work with potions . Yes you can use it

If the splash potions don't work with u you can use ItemEffect (a plugins for make effect directly to potions ) 

But if you want a stable version I advice you https://github.com/TesseractTeam/Tesseract
Yours sincerely.
